package a.i.b.a.c.d.a.c;

import a.i.b.a.c.b.ap;
import a.i.b.a.c.b.y;
import a.i.b.a.c.d.a.a;
import a.i.b.a.c.d.a.a.f;
import a.i.b.a.c.d.a.a.g;
import a.i.b.a.c.d.a.a.k;
import a.i.b.a.c.d.a.f.l;
import a.i.b.a.c.d.a.j;
import a.i.b.a.c.d.b.e;
import a.i.b.a.c.d.b.m;
import a.i.b.a.c.d.b.s;
import a.i.b.a.c.k.i;
import com.tencent.matrix.trace.core.AppMethodBeat;

public final class b {
    public final i Baf;
    public final y BcH;
    public final ap Bhr;
    public final j BmR;
    public final m BmS;
    public final e BmT;
    public final k BmU;
    public final a.i.b.a.c.j.a.m BmV;
    private final g BmW;
    public final f BmX;
    public final a.i.b.a.c.d.a.a.j BmY;
    public final a.i.b.a.c.d.a.d.b BmZ;
    public final j Bna;
    public final s Bnb;
    public final a.i.b.a.c.c.a.b Bnc;
    public final a.i.b.a.c.a.i Bnd;
    public final a Bne;
    public final l Bnf;
    public final a.i.b.a.c.d.a.k Bng;
    public final c Bnh;

    public b(i iVar, j jVar, m mVar, e eVar, k kVar, a.i.b.a.c.j.a.m mVar2, g gVar, f fVar, a.i.b.a.c.d.a.a.j jVar2, a.i.b.a.c.d.a.d.b bVar, j jVar3, s sVar, ap apVar, a.i.b.a.c.c.a.b bVar2, y yVar, a.i.b.a.c.a.i iVar2, a aVar, l lVar, a.i.b.a.c.d.a.k kVar2, c cVar) {
        a.f.b.j.p(iVar, "storageManager");
        a.f.b.j.p(jVar, "finder");
        a.f.b.j.p(mVar, "kotlinClassFinder");
        a.f.b.j.p(eVar, "deserializedDescriptorResolver");
        a.f.b.j.p(kVar, "signaturePropagator");
        a.f.b.j.p(mVar2, "errorReporter");
        a.f.b.j.p(gVar, "javaResolverCache");
        a.f.b.j.p(fVar, "javaPropertyInitializerEvaluator");
        a.f.b.j.p(jVar2, "samConversionResolver");
        a.f.b.j.p(bVar, "sourceElementFactory");
        a.f.b.j.p(jVar3, "moduleClassResolver");
        a.f.b.j.p(sVar, "packagePartProvider");
        a.f.b.j.p(apVar, "supertypeLoopChecker");
        a.f.b.j.p(bVar2, "lookupTracker");
        a.f.b.j.p(yVar, "module");
        a.f.b.j.p(iVar2, "reflectionTypes");
        a.f.b.j.p(aVar, "annotationTypeQualifierResolver");
        a.f.b.j.p(lVar, "signatureEnhancement");
        a.f.b.j.p(kVar2, "javaClassesTracker");
        a.f.b.j.p(cVar, "settings");
        AppMethodBeat.i(119823);
        this.Baf = iVar;
        this.BmR = jVar;
        this.BmS = mVar;
        this.BmT = eVar;
        this.BmU = kVar;
        this.BmV = mVar2;
        this.BmW = gVar;
        this.BmX = fVar;
        this.BmY = jVar2;
        this.BmZ = bVar;
        this.Bna = jVar3;
        this.Bnb = sVar;
        this.Bhr = apVar;
        this.Bnc = bVar2;
        this.BcH = yVar;
        this.Bnd = iVar2;
        this.Bne = aVar;
        this.Bnf = lVar;
        this.Bng = kVar2;
        this.Bnh = cVar;
        AppMethodBeat.o(119823);
    }
}
