package com.tencent.ttpic;

import com.tencent.view.d;

public class FilterEnum4Shaka extends d {
    public static final int MIC_SHAKA_ADD2_12 = 1047;
    public static final int MIC_SHAKA_ADD2_17 = 1052;
    public static final int MIC_SHAKA_ADD2_18 = 1053;
    public static final int MIC_SHAKA_ADD2_2 = 1037;
    public static final int MIC_SHAKA_ADD2_22 = 1057;
    public static final int MIC_SHAKA_ADD2_8 = 1043;
    public static final int MIC_SHAKA_ADD2_9 = 1044;
    public static final int MIC_SHAKA_ADD_13 = 1032;
    public static final int MIC_SHAKA_ADD_4 = 1023;
    public static final int MIC_SHAKA_BAOLILAI = 1015;
    public static final int MIC_SHAKA_BEIJINLAN = 1016;
    public static final int MIC_SHAKA_CANDY = 1017;
    public static final int MIC_SHAKA_CHANG = 1019;
    public static final int MIC_SHAKA_DIAN_YING = 1003;
    public static final int MIC_SHAKA_FENG_DAN = 1004;
    public static final int MIC_SHAKA_GE_HUANG = 1002;
    public static final int MIC_SHAKA_GIRL = 1013;
    public static final int MIC_SHAKA_HEI_SEN_LIN = 1000;
    public static final int MIC_SHAKA_HOLIDAY = 1014;
    public static final int MIC_SHAKA_JING_MI = 1009;
    public static final int MIC_SHAKA_MA_KA_LONG = 1001;
    public static final int MIC_SHAKA_NING_MENG = 1005;
    public static final int MIC_SHAKA_NUANNUAN = 1018;
    public static final int MIC_SHAKA_TAN_SHAO = 1012;
    public static final int MIC_SHAKA_THEME_SHISHANG_RED = 1007;
    public static final int MIC_SHAKA_THEME_SHISHANG_YELLOW = 1006;
    public static final int MIC_SHAKA_WANG_SHI = 1010;
    public static final int MIC_SHAKA_YANG_GUANG = 1011;
    public static final int MIC_WEISHI_BAIHUA = 1064;
    public static final int MIC_WEISHI_BAIXIANG = 1063;
    public static final int MIC_WEISHI_CHAZHI = 1074;
    public static final int MIC_WEISHI_FEIHONG = 1066;
    public static final int MIC_WEISHI_HAITANG = 1076;
    public static final int MIC_WEISHI_HEICHA = 1077;
    public static final int MIC_WEISHI_HUANGDAN = 1068;
    public static final int MIC_WEISHI_HUAYE = 1062;
    public static final int MIC_WEISHI_LIUJIN = 1075;
    public static final int MIC_WEISHI_LIULI = 1071;
    public static final int MIC_WEISHI_MENGHUANG = 1073;
    public static final int MIC_WEISHI_MUDAN = 1072;
    public static final int MIC_WEISHI_QINSHUI = 1061;
    public static final int MIC_WEISHI_RUOZHU = 1065;
    public static final int MIC_WEISHI_SHIZI = 1067;
    public static final int MIC_WEISHI_SHUILAN = 1069;
    public static final int MIC_WEISHI_XINXUE = 1070;
    public static final int MIC_WEISHI_v4_4_BUDING = 1087;
    public static final int MIC_WEISHI_v4_4_CHENGJING = 1094;
    public static final int MIC_WEISHI_v4_4_CHUNJIE = 1083;
    public static final int MIC_WEISHI_v4_4_CHUXUE = 1088;
    public static final int MIC_WEISHI_v4_4_HEIBAI = 1093;
    public static final int MIC_WEISHI_v4_4_HONGJIU = 1089;
    public static final int MIC_WEISHI_v4_4_HUAYANG = 1092;
    public static final int MIC_WEISHI_v4_4_HUOLI = 1102;
    public static final int MIC_WEISHI_v4_4_LANMEI = 1090;
    public static final int MIC_WEISHI_v4_4_LAODIANYING = 1096;
    public static final int MIC_WEISHI_v4_4_LIANKONG = 1095;
    public static final int MIC_WEISHI_v4_4_MAKALONG = 1086;
    public static final int MIC_WEISHI_v4_4_MEIWEI = 1097;
    public static final int MIC_WEISHI_v4_4_NAICHA = 1091;
    public static final int MIC_WEISHI_v4_4_NORMAL = 1078;
    public static final int MIC_WEISHI_v4_4_NORMAL_BACKCAMEA = 1100;
    public static final int MIC_WEISHI_v4_4_QINGCHE = 1081;
    public static final int MIC_WEISHI_v4_4_QINGCHEN = 1084;
    public static final int MIC_WEISHI_v4_4_QINGZHUANWA = 1101;
    public static final int MIC_WEISHI_v4_4_TIANPIN = 1099;
    public static final int MIC_WEISHI_v4_4_XINDONG = 1082;
    public static final int MIC_WEISHI_v4_4_XINXIAN = 1098;
    public static final int MIC_WEISHI_v4_4_YINGTAO = 1085;
    public static final int MIC_WEISHI_v4_4_ZIRAN = 1080;
    public static final int MIC_WEISHI_v4_4_ZIRAN_BACKCAMERA = 1079;
    public static final int SHAKA_FILTER_START_INDEX = 1000;

    public static boolean contains(int i) {
        return i >= 1000;
    }
}
