package com.tencent.mm.plugin.downloader.f;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.g.c.br;
import com.tencent.sqlitelint.behaviour.persistence.IssueStorage;
import com.tencent.tmassistantsdk.downloadservice.DownloadInfo;
import com.tencent.tmassistantsdk.openSDK.QQDownloader.AssistantStore.DownloadInfos.DownloadInfoColumns;
import java.lang.reflect.Field;

public final class a extends br {
    protected static com.tencent.mm.sdk.e.c.a ccO;

    public final com.tencent.mm.sdk.e.c.a Ag() {
        return ccO;
    }

    static {
        AppMethodBeat.i(2481);
        com.tencent.mm.sdk.e.c.a aVar = new com.tencent.mm.sdk.e.c.a();
        aVar.xDb = new Field[33];
        aVar.columns = new String[34];
        StringBuilder stringBuilder = new StringBuilder();
        aVar.columns[0] = "downloadId";
        aVar.xDd.put("downloadId", "LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(" downloadId LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(", ");
        aVar.xDc = "downloadId";
        aVar.columns[1] = "downloadUrl";
        aVar.xDd.put("downloadUrl", "TEXT default '' ");
        stringBuilder.append(" downloadUrl TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[2] = DownloadInfo.SECONDARYURL;
        aVar.xDd.put(DownloadInfo.SECONDARYURL, "TEXT default '' ");
        stringBuilder.append(" secondaryUrl TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[3] = "fileSize";
        aVar.xDd.put("fileSize", "LONG default '0' ");
        stringBuilder.append(" fileSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[4] = DownloadInfo.FILENAME;
        aVar.xDd.put(DownloadInfo.FILENAME, "TEXT default '' ");
        stringBuilder.append(" fileName TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[5] = "filePath";
        aVar.xDd.put("filePath", "TEXT default '' ");
        stringBuilder.append(" filePath TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[6] = "fileType";
        aVar.xDd.put("fileType", "INTEGER default '0' ");
        stringBuilder.append(" fileType INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[7] = "status";
        aVar.xDd.put("status", "INTEGER default '0' ");
        stringBuilder.append(" status INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[8] = "md5";
        aVar.xDd.put("md5", "TEXT default '' ");
        stringBuilder.append(" md5 TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[9] = "autoInstall";
        aVar.xDd.put("autoInstall", "INTEGER default 'false' ");
        stringBuilder.append(" autoInstall INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[10] = "showNotification";
        aVar.xDd.put("showNotification", "INTEGER default 'false' ");
        stringBuilder.append(" showNotification INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[11] = "sysDownloadId";
        aVar.xDd.put("sysDownloadId", "LONG default '-1' ");
        stringBuilder.append(" sysDownloadId LONG default '-1' ");
        stringBuilder.append(", ");
        aVar.columns[12] = "downloaderType";
        aVar.xDd.put("downloaderType", "INTEGER default '0' ");
        stringBuilder.append(" downloaderType INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[13] = "appId";
        aVar.xDd.put("appId", "TEXT default '' ");
        stringBuilder.append(" appId TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[14] = "downloadUrlHashCode";
        aVar.xDd.put("downloadUrlHashCode", "INTEGER default '0' ");
        stringBuilder.append(" downloadUrlHashCode INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[15] = DownloadInfoColumns.PACKAGENAME;
        aVar.xDd.put(DownloadInfoColumns.PACKAGENAME, "TEXT default '' ");
        stringBuilder.append(" packageName TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[16] = "downloadedSize";
        aVar.xDd.put("downloadedSize", "LONG default '0' ");
        stringBuilder.append(" downloadedSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[17] = "totalSize";
        aVar.xDd.put("totalSize", "LONG default '0' ");
        stringBuilder.append(" totalSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[18] = "autoDownload";
        aVar.xDd.put("autoDownload", "INTEGER default 'false' ");
        stringBuilder.append(" autoDownload INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[19] = DownloadInfoColumns.CHANNELID;
        aVar.xDd.put(DownloadInfoColumns.CHANNELID, "TEXT default '' ");
        stringBuilder.append(" channelId TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[20] = "scene";
        aVar.xDd.put("scene", "INTEGER default '0' ");
        stringBuilder.append(" scene INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[21] = "errCode";
        aVar.xDd.put("errCode", "INTEGER default '0' ");
        stringBuilder.append(" errCode INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[22] = "startTime";
        aVar.xDd.put("startTime", "LONG default '0' ");
        stringBuilder.append(" startTime LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[23] = "startSize";
        aVar.xDd.put("startSize", "LONG default '0' ");
        stringBuilder.append(" startSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[24] = "startState";
        aVar.xDd.put("startState", "INTEGER default '0' ");
        stringBuilder.append(" startState INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[25] = "fromWeApp";
        aVar.xDd.put("fromWeApp", "INTEGER default 'false' ");
        stringBuilder.append(" fromWeApp INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[26] = "downloadInWifi";
        aVar.xDd.put("downloadInWifi", "INTEGER default 'false' ");
        stringBuilder.append(" downloadInWifi INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[27] = IssueStorage.COLUMN_EXT_INFO;
        aVar.xDd.put(IssueStorage.COLUMN_EXT_INFO, "TEXT default '' ");
        stringBuilder.append(" extInfo TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[28] = "finishTime";
        aVar.xDd.put("finishTime", "LONG default '0' ");
        stringBuilder.append(" finishTime LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[29] = "isSecondDownload";
        aVar.xDd.put("isSecondDownload", "INTEGER default 'false' ");
        stringBuilder.append(" isSecondDownload INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[30] = "fromDownloadApp";
        aVar.xDd.put("fromDownloadApp", "INTEGER default 'false' ");
        stringBuilder.append(" fromDownloadApp INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[31] = "updateTime";
        aVar.xDd.put("updateTime", "LONG default '0' ");
        stringBuilder.append(" updateTime LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[32] = "reserveInWifi";
        aVar.xDd.put("reserveInWifi", "INTEGER default 'false' ");
        stringBuilder.append(" reserveInWifi INTEGER default 'false' ");
        aVar.columns[33] = "rowid";
        aVar.sql = stringBuilder.toString();
        ccO = aVar;
        AppMethodBeat.o(2481);
    }
}
