package a.i.b.a.c.j.a;

import a.i.b.a.c.b.b.a;
import a.i.b.a.c.b.f;
import a.i.b.a.c.b.w;
import a.i.b.a.c.e.a.aa;
import a.i.b.a.c.e.a.ae;
import a.i.b.a.c.e.a.ao;
import a.i.b.a.c.e.a.c.b;
import a.i.b.a.c.e.a.q;
import a.i.b.a.c.e.a.r;
import com.tencent.matrix.trace.core.AppMethodBeat;

public final /* synthetic */ class u {
    public static final /* synthetic */ int[] BCe;
    public static final /* synthetic */ int[] BCf;
    public static final /* synthetic */ int[] BHA;
    public static final /* synthetic */ int[] BHB;
    public static final /* synthetic */ int[] BHy;
    public static final /* synthetic */ int[] BHz;
    public static final /* synthetic */ int[] eQZ;
    public static final /* synthetic */ int[] pCY;
    public static final /* synthetic */ int[] pEv;

    static {
        AppMethodBeat.i(122298);
        int[] iArr = new int[q.values().length];
        eQZ = iArr;
        iArr[q.DECLARATION.ordinal()] = 1;
        eQZ[q.FAKE_OVERRIDE.ordinal()] = 2;
        eQZ[q.DELEGATION.ordinal()] = 3;
        eQZ[q.SYNTHESIZED.ordinal()] = 4;
        iArr = new int[a.values().length];
        pCY = iArr;
        iArr[a.DECLARATION.ordinal()] = 1;
        pCY[a.FAKE_OVERRIDE.ordinal()] = 2;
        pCY[a.DELEGATION.ordinal()] = 3;
        pCY[a.SYNTHESIZED.ordinal()] = 4;
        iArr = new int[r.values().length];
        pEv = iArr;
        iArr[r.FINAL.ordinal()] = 1;
        pEv[r.OPEN.ordinal()] = 2;
        pEv[r.ABSTRACT.ordinal()] = 3;
        pEv[r.SEALED.ordinal()] = 4;
        iArr = new int[w.values().length];
        BCe = iArr;
        iArr[w.FINAL.ordinal()] = 1;
        BCe[w.OPEN.ordinal()] = 2;
        BCe[w.ABSTRACT.ordinal()] = 3;
        BCe[w.SEALED.ordinal()] = 4;
        iArr = new int[ao.values().length];
        BCf = iArr;
        iArr[ao.INTERNAL.ordinal()] = 1;
        BCf[ao.PRIVATE.ordinal()] = 2;
        BCf[ao.PRIVATE_TO_THIS.ordinal()] = 3;
        BCf[ao.PROTECTED.ordinal()] = 4;
        BCf[ao.PUBLIC.ordinal()] = 5;
        BCf[ao.LOCAL.ordinal()] = 6;
        iArr = new int[b.values().length];
        BHy = iArr;
        iArr[b.CLASS.ordinal()] = 1;
        BHy[b.INTERFACE.ordinal()] = 2;
        BHy[b.ENUM_CLASS.ordinal()] = 3;
        BHy[b.ENUM_ENTRY.ordinal()] = 4;
        BHy[b.ANNOTATION_CLASS.ordinal()] = 5;
        BHy[b.OBJECT.ordinal()] = 6;
        BHy[b.COMPANION_OBJECT.ordinal()] = 7;
        iArr = new int[f.values().length];
        BHz = iArr;
        iArr[f.CLASS.ordinal()] = 1;
        BHz[f.INTERFACE.ordinal()] = 2;
        BHz[f.ENUM_CLASS.ordinal()] = 3;
        BHz[f.ENUM_ENTRY.ordinal()] = 4;
        BHz[f.ANNOTATION_CLASS.ordinal()] = 5;
        BHz[f.OBJECT.ordinal()] = 6;
        iArr = new int[ae.b.values().length];
        BHA = iArr;
        iArr[ae.b.IN.ordinal()] = 1;
        BHA[ae.b.OUT.ordinal()] = 2;
        BHA[ae.b.INV.ordinal()] = 3;
        iArr = new int[aa.a.b.values().length];
        BHB = iArr;
        iArr[aa.a.b.IN.ordinal()] = 1;
        BHB[aa.a.b.OUT.ordinal()] = 2;
        BHB[aa.a.b.INV.ordinal()] = 3;
        BHB[aa.a.b.STAR.ordinal()] = 4;
        AppMethodBeat.o(122298);
    }
}
