package com.tencent.mm.plugin.sns.ui;

import com.tencent.mm.plugin.sns.data.d;
import com.tencent.mm.plugin.sns.storage.a;
import com.tencent.mm.plugin.sns.storage.b;
import com.tencent.mm.plugin.sns.storage.n;
import com.tencent.mm.protocal.protobuf.TimeLineObject;
import com.tencent.mm.protocal.protobuf.bav;
import com.tencent.mm.protocal.protobuf.cbf;

public final class av {
    public int auo;
    public String igi;
    public String mAppName;
    public cbf qBX;
    public n qBY;
    public TimeLineObject qCc;
    public String rAA;
    public a rAB;
    public b rAC;
    public String rAD;
    public String rAE;
    public String rAF;
    public String rAG;
    public String rAH;
    public boolean rAI;
    public boolean rAJ;
    public boolean rAK;
    public int rAL;
    public boolean rAM;
    public String rAN;
    public boolean rAO;
    public boolean rAP;
    public boolean rAQ;
    public boolean rAR;
    public String rAS;
    public String rAT;
    public boolean rAU;
    public boolean rAV;
    public int rAW;
    public boolean rAX;
    public boolean rAY;
    public String rAZ;
    public d rAp;
    public CharSequence rAq = null;
    public com.tencent.mm.n.a rAr;
    public String rAs;
    public long rAt;
    public String rAu;
    public int rAv;
    public int rAw;
    public int rAx;
    public boolean rAy;
    public String rAz;
    public boolean rBa;
    public boolean rBb;
    public int rBc;
    public double rBd;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rBe;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rBf;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rBg;
    public boolean rBh;
    public String rBi;
    public bav rBj;
    public boolean rgZ;
    public String riA;
}
