package com.tencent.p177mm.compatible.p221e;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.p177mm.sdk.platformtools.C4990ab;

/* renamed from: com.tencent.mm.compatible.e.k */
public final class C1419k {
    public int erI = -1;
    public int erJ = -1;
    public int erK = -1;
    public int erL = -1;
    public int erM = -1;
    public int erN = -1;
    public int erO = -1;
    public int erP = -1;
    public boolean erQ = false;
    public int erR = -1;
    public int erS = -1;
    public int erT = -1;
    public int erU = -1;
    public int erV = -1;
    public int erW = -1;
    public int erX = -1;
    public int erY = -1;
    public int erZ = -1;
    public String esA = null;
    public String esB = null;
    public int esC = -1;
    public int esD = 2;
    public int esE = 1;
    public int esF = 1;
    public int esG = -1;
    public int esH = -1;
    public int esI = -1;
    public int esa = -1;
    public int esb = -1;
    public int esc = -1;
    public int esd = -1;
    public int ese = -1;
    public int esf = -1;
    public int esg = -1;
    public int esh = -1;
    public int esi = -1;
    public int esj = -1;
    public double esk = -1.0d;
    public int esl = -1;
    public int esm = -1;
    public int esn = -1;
    public int eso = -1;
    public String esp = null;
    public String esq = null;
    public String esr = null;
    public String ess = null;
    public String est = null;
    public String esu = null;
    public String esv = null;
    public String esw = null;
    public String esx = null;
    public String esy = null;
    public String esz = null;

    public C1419k() {
        AppMethodBeat.m2504i(92933);
        reset();
        AppMethodBeat.m2505o(92933);
    }

    public final void reset() {
        this.erI = -1;
        this.erJ = -1;
        this.erK = -1;
        this.erL = -1;
        this.erM = -1;
        this.erN = -1;
        this.erP = -1;
        this.erO = -1;
        this.erS = -1;
        this.erT = -1;
        this.erU = -1;
        this.erV = -1;
        this.erQ = false;
        this.erR = -1;
        this.erW = -1;
        this.erX = -1;
        this.erY = -1;
        this.erZ = -1;
        this.esa = -1;
        this.esd = -1;
        this.esc = -1;
        this.ese = -1;
        this.esf = -1;
        this.esb = -1;
        this.ese = -1;
        this.esf = -1;
        this.esi = -1;
        this.esl = -1;
        this.esm = -1;
        this.esn = -1;
        this.eso = -1;
        this.esp = null;
        this.esq = null;
        this.esr = null;
        this.ess = null;
        this.esg = -1;
        this.est = null;
        this.esu = null;
        this.esv = null;
        this.esw = null;
        this.esx = null;
        this.esy = null;
        this.esh = -1;
        this.esz = null;
        this.esA = null;
        this.esB = null;
        this.esC = -1;
        this.esD = 2;
        this.esE = 1;
        this.esF = 1;
        this.esj = -1;
        this.esH = -1;
        this.esI = -1;
    }

    public final void dump() {
        AppMethodBeat.m2504i(92934);
        C4990ab.m7410d("MicroMsg.CommonInfo", "js " + this.erI);
        C4990ab.m7410d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.erJ);
        C4990ab.m7410d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.erK);
        C4990ab.m7410d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.erM);
        C4990ab.m7410d("MicroMsg.CommonInfo", "startBluetoothSco " + this.erL);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.erN);
        C4990ab.m7410d("MicroMsg.CommonInfo", "pcmReadMode " + this.erP);
        C4990ab.m7410d("MicroMsg.CommonInfo", "pcmBufferRate " + this.erO);
        C4990ab.m7410d("MicroMsg.CommonInfo", "audioPrePro " + this.erS);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voicemsgfd " + this.erT);
        C4990ab.m7410d("MicroMsg.CommonInfo", "htcvoicemode " + this.erU);
        C4990ab.m7410d("MicroMsg.CommonInfo", "samsungvoicemode " + this.erV);
        C4990ab.m7410d("MicroMsg.CommonInfo", "speexBufferRate " + this.erW);
        C4990ab.m7410d("MicroMsg.CommonInfo", "linespe " + this.erX);
        C4990ab.m7410d("MicroMsg.CommonInfo", "fixspan " + this.esi);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extvideo " + this.erY);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extvideosam " + this.erZ);
        C4990ab.m7410d("MicroMsg.CommonInfo", "sysvideodegree " + this.esa);
        C4990ab.m7410d("MicroMsg.CommonInfo", "mmnotify " + this.esd);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extsharevcard " + this.esc);
        C4990ab.m7410d("MicroMsg.CommonInfo", "audioformat " + this.ese);
        C4990ab.m7410d("MicroMsg.CommonInfo", "qrcam " + this.esf);
        C4990ab.m7410d("MicroMsg.CommonInfo", "mBase " + this.esp);
        C4990ab.m7410d("MicroMsg.CommonInfo", "mPackageInfo " + this.esq);
        C4990ab.m7410d("MicroMsg.CommonInfo", "mClassLoader " + this.esr);
        C4990ab.m7410d("MicroMsg.CommonInfo", "mResources " + this.ess);
        C4990ab.m7410d("MicroMsg.CommonInfo", "sysvideofp " + this.esg);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extstoragedir " + this.est);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extpubdir " + this.esu);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extdatadir " + this.esv);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extrootdir " + this.esw);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extstoragestate " + this.esx);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extcachedir " + this.esy);
        C4990ab.m7410d("MicroMsg.CommonInfo", "extvideoplayer " + this.esh);
        C4990ab.m7410d("MicroMsg.CommonInfo", "loadDrawable " + this.esz);
        C4990ab.m7410d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.esA);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.esl);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.esm);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.esn);
        C4990ab.m7410d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.eso);
        C4990ab.m7410d("MicroMsg.CommonInfo", "sight full screen type " + this.esB);
        C4990ab.m7410d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.esD);
        C4990ab.m7410d("MicroMsg.CommonInfo", "swipeBackConfig " + this.esE);
        C4990ab.m7410d("MicroMsg.CommonInfo", "qrCodeZoom " + this.esj);
        C4990ab.m7410d("MicroMsg.CommonInfo", "hevcTransCodeMediaCodec" + this.esH);
        C4990ab.m7416i("MicroMsg.CommonInfo", "videoSupportHevcDecode" + this.esI);
        AppMethodBeat.m2505o(92934);
    }
}
