package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.StatusListener;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.Preconditions;
import com.tencent.matrix.trace.core.AppMethodBeat;
import java.util.concurrent.TimeUnit;

public final class zzbx<R extends Result> extends PendingResult<R> {
    private final Status mStatus;

    public zzbx(Status status) {
        AppMethodBeat.m2504i(60854);
        Preconditions.checkNotNull(status, "Status must not be null");
        Preconditions.checkArgument(!status.isSuccess(), "Status must not be success");
        this.mStatus = status;
        AppMethodBeat.m2505o(60854);
    }

    public final void addStatusListener(StatusListener statusListener) {
        AppMethodBeat.m2504i(60861);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60861);
        throw unsupportedOperationException;
    }

    public final R await() {
        AppMethodBeat.m2504i(60855);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60855);
        throw unsupportedOperationException;
    }

    public final R await(long j, TimeUnit timeUnit) {
        AppMethodBeat.m2504i(60856);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60856);
        throw unsupportedOperationException;
    }

    public final void cancel() {
        AppMethodBeat.m2504i(60857);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60857);
        throw unsupportedOperationException;
    }

    /* Access modifiers changed, original: final */
    public final Status getStatus() {
        return this.mStatus;
    }

    public final boolean isCanceled() {
        AppMethodBeat.m2504i(60858);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60858);
        throw unsupportedOperationException;
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        AppMethodBeat.m2504i(60859);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60859);
        throw unsupportedOperationException;
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        AppMethodBeat.m2504i(60860);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60860);
        throw unsupportedOperationException;
    }

    public final <S extends Result> TransformedResult<S> then(ResultTransform<? super R, ? extends S> resultTransform) {
        AppMethodBeat.m2504i(60862);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60862);
        throw unsupportedOperationException;
    }

    public final Integer zzo() {
        AppMethodBeat.m2504i(60863);
        UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
        AppMethodBeat.m2505o(60863);
        throw unsupportedOperationException;
    }
}
