package com.tencent.p177mm.plugin.downloader.p1607f;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.p177mm.p230g.p711c.C9521br;
import com.tencent.p177mm.sdk.p603e.C4925c.C4924a;
import com.tencent.sqlitelint.behaviour.persistence.IssueStorage;
import com.tencent.tmassistantsdk.downloadservice.DownloadInfo;
import com.tencent.tmassistantsdk.openSDK.QQDownloader.AssistantStore.DownloadInfos.DownloadInfoColumns;
import java.lang.reflect.Field;

/* renamed from: com.tencent.mm.plugin.downloader.f.a */
public final class C42911a extends C9521br {
    protected static C4924a ccO;

    /* renamed from: Ag */
    public final C4924a mo4635Ag() {
        return ccO;
    }

    static {
        AppMethodBeat.m2504i(2481);
        C4924a c4924a = new C4924a();
        c4924a.xDb = new Field[33];
        c4924a.columns = new String[34];
        StringBuilder stringBuilder = new StringBuilder();
        c4924a.columns[0] = "downloadId";
        c4924a.xDd.put("downloadId", "LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(" downloadId LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(", ");
        c4924a.xDc = "downloadId";
        c4924a.columns[1] = "downloadUrl";
        c4924a.xDd.put("downloadUrl", "TEXT default '' ");
        stringBuilder.append(" downloadUrl TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[2] = DownloadInfo.SECONDARYURL;
        c4924a.xDd.put(DownloadInfo.SECONDARYURL, "TEXT default '' ");
        stringBuilder.append(" secondaryUrl TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[3] = "fileSize";
        c4924a.xDd.put("fileSize", "LONG default '0' ");
        stringBuilder.append(" fileSize LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[4] = DownloadInfo.FILENAME;
        c4924a.xDd.put(DownloadInfo.FILENAME, "TEXT default '' ");
        stringBuilder.append(" fileName TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[5] = "filePath";
        c4924a.xDd.put("filePath", "TEXT default '' ");
        stringBuilder.append(" filePath TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[6] = "fileType";
        c4924a.xDd.put("fileType", "INTEGER default '0' ");
        stringBuilder.append(" fileType INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[7] = "status";
        c4924a.xDd.put("status", "INTEGER default '0' ");
        stringBuilder.append(" status INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[8] = "md5";
        c4924a.xDd.put("md5", "TEXT default '' ");
        stringBuilder.append(" md5 TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[9] = "autoInstall";
        c4924a.xDd.put("autoInstall", "INTEGER default 'false' ");
        stringBuilder.append(" autoInstall INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[10] = "showNotification";
        c4924a.xDd.put("showNotification", "INTEGER default 'false' ");
        stringBuilder.append(" showNotification INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[11] = "sysDownloadId";
        c4924a.xDd.put("sysDownloadId", "LONG default '-1' ");
        stringBuilder.append(" sysDownloadId LONG default '-1' ");
        stringBuilder.append(", ");
        c4924a.columns[12] = "downloaderType";
        c4924a.xDd.put("downloaderType", "INTEGER default '0' ");
        stringBuilder.append(" downloaderType INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[13] = "appId";
        c4924a.xDd.put("appId", "TEXT default '' ");
        stringBuilder.append(" appId TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[14] = "downloadUrlHashCode";
        c4924a.xDd.put("downloadUrlHashCode", "INTEGER default '0' ");
        stringBuilder.append(" downloadUrlHashCode INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[15] = DownloadInfoColumns.PACKAGENAME;
        c4924a.xDd.put(DownloadInfoColumns.PACKAGENAME, "TEXT default '' ");
        stringBuilder.append(" packageName TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[16] = "downloadedSize";
        c4924a.xDd.put("downloadedSize", "LONG default '0' ");
        stringBuilder.append(" downloadedSize LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[17] = "totalSize";
        c4924a.xDd.put("totalSize", "LONG default '0' ");
        stringBuilder.append(" totalSize LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[18] = "autoDownload";
        c4924a.xDd.put("autoDownload", "INTEGER default 'false' ");
        stringBuilder.append(" autoDownload INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[19] = DownloadInfoColumns.CHANNELID;
        c4924a.xDd.put(DownloadInfoColumns.CHANNELID, "TEXT default '' ");
        stringBuilder.append(" channelId TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[20] = "scene";
        c4924a.xDd.put("scene", "INTEGER default '0' ");
        stringBuilder.append(" scene INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[21] = "errCode";
        c4924a.xDd.put("errCode", "INTEGER default '0' ");
        stringBuilder.append(" errCode INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[22] = "startTime";
        c4924a.xDd.put("startTime", "LONG default '0' ");
        stringBuilder.append(" startTime LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[23] = "startSize";
        c4924a.xDd.put("startSize", "LONG default '0' ");
        stringBuilder.append(" startSize LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[24] = "startState";
        c4924a.xDd.put("startState", "INTEGER default '0' ");
        stringBuilder.append(" startState INTEGER default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[25] = "fromWeApp";
        c4924a.xDd.put("fromWeApp", "INTEGER default 'false' ");
        stringBuilder.append(" fromWeApp INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[26] = "downloadInWifi";
        c4924a.xDd.put("downloadInWifi", "INTEGER default 'false' ");
        stringBuilder.append(" downloadInWifi INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[27] = IssueStorage.COLUMN_EXT_INFO;
        c4924a.xDd.put(IssueStorage.COLUMN_EXT_INFO, "TEXT default '' ");
        stringBuilder.append(" extInfo TEXT default '' ");
        stringBuilder.append(", ");
        c4924a.columns[28] = "finishTime";
        c4924a.xDd.put("finishTime", "LONG default '0' ");
        stringBuilder.append(" finishTime LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[29] = "isSecondDownload";
        c4924a.xDd.put("isSecondDownload", "INTEGER default 'false' ");
        stringBuilder.append(" isSecondDownload INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[30] = "fromDownloadApp";
        c4924a.xDd.put("fromDownloadApp", "INTEGER default 'false' ");
        stringBuilder.append(" fromDownloadApp INTEGER default 'false' ");
        stringBuilder.append(", ");
        c4924a.columns[31] = "updateTime";
        c4924a.xDd.put("updateTime", "LONG default '0' ");
        stringBuilder.append(" updateTime LONG default '0' ");
        stringBuilder.append(", ");
        c4924a.columns[32] = "reserveInWifi";
        c4924a.xDd.put("reserveInWifi", "INTEGER default 'false' ");
        stringBuilder.append(" reserveInWifi INTEGER default 'false' ");
        c4924a.columns[33] = "rowid";
        c4924a.sql = stringBuilder.toString();
        ccO = c4924a;
        AppMethodBeat.m2505o(2481);
    }
}
