package com.tencent.mm.ui.tools;

import android.app.Dialog;
import android.app.TimePickerDialog;
import android.app.TimePickerDialog.OnTimeSetListener;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.MenuItem.OnMenuItemClickListener;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.TimePicker;
import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.R;
import com.tencent.mm.hardcoder.WXHardCoderJNI;
import com.tencent.mm.hardcoder.i;
import com.tencent.mm.plugin.hardcoder.a;
import com.tencent.mm.pluginsdk.f.h;
import com.tencent.mm.sdk.platformtools.aa;
import com.tencent.mm.sdk.platformtools.ab;
import com.tencent.mm.sdk.platformtools.ah;
import com.tencent.mm.sdk.platformtools.bo;
import com.tencent.mm.ui.MMActivity;
import java.sql.Time;
import java.text.DateFormat;

public class HardCoderSettingUI extends MMActivity {
    private boolean qmI = false;
    private final OnTimeSetListener qmJ = new OnTimeSetListener() {
        public final void onTimeSet(TimePicker timePicker, int i, int i2) {
            AppMethodBeat.i(34874);
            if (HardCoderSettingUI.this.qmI) {
                WXHardCoderJNI.hcBeginTimeHour = i;
                WXHardCoderJNI.hcBeginTimeMin = i2;
                HardCoderSettingUI.this.zCp.setText(HardCoderSettingUI.h(HardCoderSettingUI.this, WXHardCoderJNI.hcBeginTimeHour, WXHardCoderJNI.hcBeginTimeMin));
                AppMethodBeat.o(34874);
                return;
            }
            WXHardCoderJNI.hcEndTimeHour = i;
            WXHardCoderJNI.hcEndTimeMin = i2;
            HardCoderSettingUI.this.zCq.setText(HardCoderSettingUI.h(HardCoderSettingUI.this, WXHardCoderJNI.hcEndTimeHour, WXHardCoderJNI.hcEndTimeMin));
            AppMethodBeat.o(34874);
        }
    };
    private EditText zCA;
    private EditText zCB;
    private Spinner zCC;
    private Spinner zCD;
    private CheckBox zCE;
    private CheckBox zCF;
    private EditText zCG;
    private EditText zCH;
    private EditText zCI;
    private Spinner zCJ;
    private Spinner zCK;
    private CheckBox zCL;
    private CheckBox zCM;
    private EditText zCN;
    private EditText zCO;
    private EditText zCP;
    private Spinner zCQ;
    private Spinner zCR;
    private CheckBox zCS;
    private CheckBox zCT;
    private EditText zCU;
    private EditText zCV;
    private EditText zCW;
    private Spinner zCX;
    private Spinner zCY;
    private CheckBox zCZ;
    private CheckBox zCk;
    private EditText zCl;
    private CheckBox zCm;
    private CheckBox zCn;
    private CheckBox zCo;
    private TextView zCp;
    private TextView zCq;
    private CheckBox zCr;
    private EditText zCs;
    private EditText zCt;
    private EditText zCu;
    private Spinner zCv;
    private Spinner zCw;
    private CheckBox zCx;
    private CheckBox zCy;
    private EditText zCz;
    private EditText zDA;
    private EditText zDB;
    private EditText zDC;
    private Spinner zDD;
    private Spinner zDE;
    private CheckBox zDF;
    private CheckBox zDG;
    private EditText zDH;
    private EditText zDI;
    private EditText zDJ;
    private Spinner zDK;
    private Spinner zDL;
    private CheckBox zDM;
    private CheckBox zDN;
    private EditText zDO;
    private EditText zDP;
    private EditText zDQ;
    private Spinner zDR;
    private Spinner zDS;
    private CheckBox zDT;
    private CheckBox zDU;
    private EditText zDV;
    private EditText zDW;
    private EditText zDX;
    private Spinner zDY;
    private Spinner zDZ;
    private CheckBox zDa;
    private EditText zDb;
    private EditText zDc;
    private EditText zDd;
    private Spinner zDe;
    private Spinner zDf;
    private CheckBox zDg;
    private CheckBox zDh;
    private EditText zDi;
    private EditText zDj;
    private EditText zDk;
    private Spinner zDl;
    private Spinner zDm;
    private CheckBox zDn;
    private EditText zDo;
    private CheckBox zDp;
    private EditText zDq;
    private EditText zDr;
    private EditText zDs;
    private EditText zDt;
    private EditText zDu;
    private EditText zDv;
    private Spinner zDw;
    private Spinner zDx;
    private CheckBox zDy;
    private CheckBox zDz;
    private Spinner zEA;
    private Spinner zEB;
    private CheckBox zEC;
    private CheckBox zED;
    private EditText zEE;
    private EditText zEF;
    private EditText zEG;
    private Spinner zEH;
    private Spinner zEI;
    private CheckBox zEJ;
    private CheckBox zEK;
    private EditText zEL;
    private EditText zEM;
    private EditText zEN;
    private Spinner zEO;
    private Spinner zEP;
    private CheckBox zEQ;
    private CheckBox zEa;
    private CheckBox zEb;
    private EditText zEc;
    private EditText zEd;
    private EditText zEe;
    private Spinner zEf;
    private Spinner zEg;
    private CheckBox zEh;
    private CheckBox zEi;
    private EditText zEj;
    private EditText zEk;
    private EditText zEl;
    private Spinner zEm;
    private Spinner zEn;
    private CheckBox zEo;
    private CheckBox zEp;
    private EditText zEq;
    private EditText zEr;
    private EditText zEs;
    private Spinner zEt;
    private Spinner zEu;
    private CheckBox zEv;
    private CheckBox zEw;
    private EditText zEx;
    private EditText zEy;
    private EditText zEz;

    public void onWindowFocusChanged(boolean z) {
        super.onWindowFocusChanged(z);
        AppMethodBeat.at(this, z);
    }

    public HardCoderSettingUI() {
        AppMethodBeat.i(34875);
        AppMethodBeat.o(34875);
    }

    static /* synthetic */ String h(Context context, int i, int i2) {
        AppMethodBeat.i(34881);
        String c = c(context, i, i2);
        AppMethodBeat.o(34881);
        return c;
    }

    public void onCreate(Bundle bundle) {
        AppMethodBeat.i(34876);
        super.onCreate(bundle);
        setMMTitle((int) R.string.e7f);
        setBackBtn(new OnMenuItemClickListener() {
            public final boolean onMenuItemClick(MenuItem menuItem) {
                AppMethodBeat.i(34870);
                HardCoderSettingUI.this.finish();
                AppMethodBeat.o(34870);
                return true;
            }
        });
        SharedPreferences sharedPreferences = this.mController.ylL.getSharedPreferences(WXHardCoderJNI.SETTING_SP_FILE, 0);
        if (!sharedPreferences.contains(WXHardCoderJNI.KEY_HC_ENABLE)) {
            a(sharedPreferences.edit().putBoolean(WXHardCoderJNI.KEY_HC_ENABLE, true));
        }
        this.zCm = (CheckBox) findViewById(R.id.cag);
        this.zCm.setChecked(WXHardCoderJNI.getDebug());
        this.zCk = (CheckBox) findViewById(R.id.caf);
        this.zCk.setChecked(WXHardCoderJNI.getEnable());
        this.zCl = (EditText) findViewById(R.id.cai);
        this.zCl.setText(WXHardCoderJNI.hcRetryInterval);
        this.zCn = (CheckBox) findViewById(R.id.cah);
        this.zCo = (CheckBox) findViewById(R.id.caj);
        this.zCo.setChecked(WXHardCoderJNI.hcTimeLimit);
        this.zCp = (TextView) findViewById(R.id.cak);
        this.zCq = (TextView) findViewById(R.id.cal);
        this.zCp.setText(c(this, WXHardCoderJNI.hcBeginTimeHour, WXHardCoderJNI.hcBeginTimeMin));
        this.zCq.setText(c(this, WXHardCoderJNI.hcEndTimeHour, WXHardCoderJNI.hcEndTimeMin));
        this.zCp.setOnClickListener(new OnClickListener() {
            public final void onClick(View view) {
                AppMethodBeat.i(34871);
                HardCoderSettingUI.this.qmI = true;
                HardCoderSettingUI.this.showDialog(1);
                AppMethodBeat.o(34871);
            }
        });
        this.zCq.setOnClickListener(new OnClickListener() {
            public final void onClick(View view) {
                AppMethodBeat.i(34872);
                HardCoderSettingUI.this.qmI = false;
                HardCoderSettingUI.this.showDialog(1);
                AppMethodBeat.o(34872);
            }
        });
        this.zCr = (CheckBox) findViewById(R.id.cam);
        this.zCr.setChecked(WXHardCoderJNI.hcBootEnable);
        this.zCs = (EditText) findViewById(R.id.cao);
        this.zCs.setText(WXHardCoderJNI.hcBootDelay);
        this.zCt = (EditText) findViewById(R.id.can);
        this.zCt.setText(WXHardCoderJNI.hcBootTimeout);
        this.zCt.setSelection(this.zCt.getText().length());
        this.zCu = (EditText) findViewById(R.id.cap);
        this.zCu.setText(WXHardCoderJNI.hcBootAction);
        this.zCv = (Spinner) findViewById(R.id.caq);
        this.zCv.setSelection(WXHardCoderJNI.hcBootCPU);
        this.zCw = (Spinner) findViewById(R.id.car);
        this.zCw.setSelection(WXHardCoderJNI.hcBootIO);
        this.zCx = (CheckBox) findViewById(R.id.cas);
        this.zCx.setChecked(WXHardCoderJNI.hcBootThr);
        this.zCy = (CheckBox) findViewById(R.id.cb0);
        this.zCy.setChecked(WXHardCoderJNI.hcEnterChattingEnable);
        this.zCz = (EditText) findViewById(R.id.cb2);
        this.zCz.setText(WXHardCoderJNI.hcEnterChattingDelay);
        this.zCA = (EditText) findViewById(R.id.cb1);
        this.zCA.setText(WXHardCoderJNI.hcEnterChattingTimeout);
        this.zCA.setSelection(this.zCA.getText().length());
        this.zCB = (EditText) findViewById(R.id.cb3);
        this.zCB.setText(WXHardCoderJNI.hcEnterChattingAction);
        this.zCC = (Spinner) findViewById(R.id.cb4);
        this.zCC.setSelection(WXHardCoderJNI.hcEnterChattingCPU);
        this.zCD = (Spinner) findViewById(R.id.cb5);
        this.zCD.setSelection(WXHardCoderJNI.hcEnterChattingIO);
        this.zCE = (CheckBox) findViewById(R.id.cb6);
        this.zCE.setChecked(WXHardCoderJNI.hcEnterChattingThr);
        this.zCF = (CheckBox) findViewById(R.id.cb7);
        this.zCF.setChecked(WXHardCoderJNI.hcQuitChattingEnable);
        this.zCG = (EditText) findViewById(R.id.cb9);
        this.zCG.setText(WXHardCoderJNI.hcQuitChattingDelay);
        this.zCH = (EditText) findViewById(R.id.cb8);
        this.zCH.setText(WXHardCoderJNI.hcQuitChattingTimeout);
        this.zCH.setSelection(this.zCH.getText().length());
        this.zCI = (EditText) findViewById(R.id.cb_);
        this.zCI.setText(WXHardCoderJNI.hcQuitChattingAction);
        this.zCJ = (Spinner) findViewById(R.id.cba);
        this.zCJ.setSelection(WXHardCoderJNI.hcQuitChattingCPU);
        this.zCK = (Spinner) findViewById(R.id.cbb);
        this.zCK.setSelection(WXHardCoderJNI.hcQuitChattingIO);
        this.zCL = (CheckBox) findViewById(R.id.cbc);
        this.zCL.setChecked(WXHardCoderJNI.hcQuitChattingThr);
        this.zCM = (CheckBox) findViewById(R.id.cbk);
        this.zCM.setChecked(WXHardCoderJNI.hcSendMsgEnable);
        this.zCN = (EditText) findViewById(R.id.cbm);
        this.zCN.setText(WXHardCoderJNI.hcSendMsgDelay);
        this.zCO = (EditText) findViewById(R.id.cbl);
        this.zCO.setText(WXHardCoderJNI.hcSendMsgTimeout);
        this.zCO.setSelection(this.zCO.getText().length());
        this.zCP = (EditText) findViewById(R.id.cbn);
        this.zCP.setText(WXHardCoderJNI.hcSendMsgAction);
        this.zCQ = (Spinner) findViewById(R.id.cbo);
        this.zCQ.setSelection(WXHardCoderJNI.hcSendMsgCPU);
        this.zCR = (Spinner) findViewById(R.id.cbp);
        this.zCR.setSelection(WXHardCoderJNI.hcSendMsgIO);
        this.zCS = (CheckBox) findViewById(R.id.cbq);
        this.zCS.setChecked(WXHardCoderJNI.hcSendMsgThr);
        this.zCT = (CheckBox) findViewById(R.id.cbd);
        this.zCT.setChecked(WXHardCoderJNI.hcSendPicMsgEnable);
        this.zCU = (EditText) findViewById(R.id.cbf);
        this.zCU.setText(WXHardCoderJNI.hcSendPicMsgDelay);
        this.zCV = (EditText) findViewById(R.id.cbe);
        this.zCV.setText(WXHardCoderJNI.hcSendPicMsgTimeout);
        this.zCV.setSelection(this.zCV.getText().length());
        this.zCW = (EditText) findViewById(R.id.cbg);
        this.zCW.setText(WXHardCoderJNI.hcSendPicMsgAction);
        this.zCX = (Spinner) findViewById(R.id.cbh);
        this.zCX.setSelection(WXHardCoderJNI.hcSendPicMsgCPU);
        this.zCY = (Spinner) findViewById(R.id.cbi);
        this.zCY.setSelection(WXHardCoderJNI.hcSendPicMsgIO);
        this.zCZ = (CheckBox) findViewById(R.id.cbj);
        this.zCZ.setChecked(WXHardCoderJNI.hcSendPicMsgThr);
        this.zDa = (CheckBox) findViewById(R.id.cbr);
        this.zDa.setChecked(WXHardCoderJNI.hcReceiveMsgEnable);
        this.zDb = (EditText) findViewById(R.id.cbt);
        this.zDb.setText(WXHardCoderJNI.hcReceiveMsgDelay);
        this.zDc = (EditText) findViewById(R.id.cbs);
        this.zDc.setText(WXHardCoderJNI.hcReceiveMsgTimeout);
        this.zDc.setSelection(this.zDc.getText().length());
        this.zDd = (EditText) findViewById(R.id.cbu);
        this.zDd.setText(WXHardCoderJNI.hcReceiveMsgAction);
        this.zDe = (Spinner) findViewById(R.id.cbv);
        this.zDe.setSelection(WXHardCoderJNI.hcReceiveMsgCPU);
        this.zDf = (Spinner) findViewById(R.id.cbw);
        this.zDf.setSelection(WXHardCoderJNI.hcReceiveMsgIO);
        this.zDg = (CheckBox) findViewById(R.id.cbx);
        this.zDg.setChecked(WXHardCoderJNI.hcReceiveMsgThr);
        this.zDh = (CheckBox) findViewById(R.id.cby);
        this.zDh.setChecked(WXHardCoderJNI.hcUpdateChatroomEnable);
        this.zDi = (EditText) findViewById(R.id.cc1);
        this.zDi.setText(WXHardCoderJNI.hcUpdateChatroomDelay);
        this.zDj = (EditText) findViewById(R.id.cc0);
        this.zDj.setText(WXHardCoderJNI.hcUpdateChatroomTimeout);
        this.zDj.setSelection(this.zDj.getText().length());
        this.zDk = (EditText) findViewById(R.id.cc2);
        this.zDk.setText(WXHardCoderJNI.hcUpdateChatroomAction);
        this.zDl = (Spinner) findViewById(R.id.cc3);
        this.zDl.setSelection(WXHardCoderJNI.hcUpdateChatroomCPU);
        this.zDm = (Spinner) findViewById(R.id.cc4);
        this.zDm.setSelection(WXHardCoderJNI.hcUpdateChatroomIO);
        this.zDn = (CheckBox) findViewById(R.id.cc5);
        this.zDn.setChecked(WXHardCoderJNI.hcUpdateChatroomThr);
        this.zDo = (EditText) findViewById(R.id.cbz);
        this.zDo.setText(WXHardCoderJNI.hcUpdateChatroomMemberCount);
        this.zDp = (CheckBox) findViewById(R.id.cc6);
        this.zDp.setChecked(WXHardCoderJNI.hcDBEnable);
        this.zDq = (EditText) findViewById(R.id.cc8);
        this.zDq.setText(WXHardCoderJNI.hcDBDelayQuery);
        this.zDr = (EditText) findViewById(R.id.cca);
        this.zDr.setText(WXHardCoderJNI.hcDBDelayWrite);
        this.zDs = (EditText) findViewById(R.id.cc7);
        this.zDs.setText(WXHardCoderJNI.hcDBTimeout);
        this.zDt = (EditText) findViewById(R.id.cc_);
        this.zDt.setText(WXHardCoderJNI.hcDBTimeoutBusy);
        this.zDu = (EditText) findViewById(R.id.cc9);
        this.zDu.setText(WXHardCoderJNI.hcDBActionQuery);
        this.zDv = (EditText) findViewById(R.id.ccb);
        this.zDv.setText(WXHardCoderJNI.hcDBActionWrite);
        this.zDw = (Spinner) findViewById(R.id.ccc);
        this.zDw.setSelection(WXHardCoderJNI.hcDBCPU);
        this.zDx = (Spinner) findViewById(R.id.ccd);
        this.zDx.setSelection(WXHardCoderJNI.hcDBIO);
        this.zDy = (CheckBox) findViewById(R.id.cce);
        this.zDy.setChecked(WXHardCoderJNI.hcDBThr);
        this.zDz = (CheckBox) findViewById(R.id.cat);
        this.zDz.setChecked(WXHardCoderJNI.hcEncodeVideoEnable);
        this.zDA = (EditText) findViewById(R.id.cav);
        this.zDA.setText(WXHardCoderJNI.hcEncodeVideoDelay);
        this.zDB = (EditText) findViewById(R.id.cau);
        this.zDB.setText(WXHardCoderJNI.hcEncodeVideoTimeout);
        this.zDC = (EditText) findViewById(R.id.caw);
        this.zDC.setText(WXHardCoderJNI.hcEncodeVideoAction);
        this.zDD = (Spinner) findViewById(R.id.cax);
        this.zDD.setSelection(WXHardCoderJNI.hcEncodeVideoCPU);
        this.zDE = (Spinner) findViewById(R.id.cay);
        this.zDE.setSelection(WXHardCoderJNI.hcEncodeVideoIO);
        this.zDF = (CheckBox) findViewById(R.id.caz);
        this.zDF.setChecked(WXHardCoderJNI.hcEncodeVideoThr);
        this.zDG = (CheckBox) findViewById(R.id.ccf);
        this.zDG.setChecked(WXHardCoderJNI.hcDecodePicEnable);
        this.zDH = (EditText) findViewById(R.id.cch);
        this.zDH.setText(WXHardCoderJNI.hcDecodePicDelay);
        this.zDI = (EditText) findViewById(R.id.ccg);
        this.zDI.setText(WXHardCoderJNI.hcDecodePicTimeout);
        this.zDJ = (EditText) findViewById(R.id.cci);
        this.zDJ.setText(WXHardCoderJNI.hcDecodePicAction);
        this.zDK = (Spinner) findViewById(R.id.ccj);
        this.zDK.setSelection(WXHardCoderJNI.hcDecodePicCPU);
        this.zDL = (Spinner) findViewById(R.id.cck);
        this.zDL.setSelection(WXHardCoderJNI.hcDecodePicIO);
        this.zDM = (CheckBox) findViewById(R.id.ccl);
        this.zDM.setChecked(WXHardCoderJNI.hcDecodePicThr);
        this.zDN = (CheckBox) findViewById(R.id.ccm);
        this.zDN.setChecked(WXHardCoderJNI.hcGifEnable);
        this.zDO = (EditText) findViewById(R.id.cco);
        this.zDO.setText(WXHardCoderJNI.hcGifDelay);
        this.zDP = (EditText) findViewById(R.id.ccn);
        this.zDP.setText(WXHardCoderJNI.hcGifTimeout);
        this.zDQ = (EditText) findViewById(R.id.ccp);
        this.zDQ.setText(WXHardCoderJNI.hcGifAction);
        this.zDR = (Spinner) findViewById(R.id.ccq);
        this.zDR.setSelection(WXHardCoderJNI.hcGifCPU);
        this.zDS = (Spinner) findViewById(R.id.ccr);
        this.zDS.setSelection(WXHardCoderJNI.hcGifIO);
        this.zDT = (CheckBox) findViewById(R.id.ccs);
        this.zDT.setChecked(WXHardCoderJNI.hcGifThr);
        this.zDU = (CheckBox) findViewById(R.id.cct);
        this.zDU.setChecked(WXHardCoderJNI.hcGifFrameEnable);
        this.zDV = (EditText) findViewById(R.id.ccv);
        this.zDV.setText(WXHardCoderJNI.hcGifFrameDelay);
        this.zDW = (EditText) findViewById(R.id.ccu);
        this.zDW.setText(WXHardCoderJNI.hcGifFrameTimeout);
        this.zDX = (EditText) findViewById(R.id.ccw);
        this.zDX.setText(WXHardCoderJNI.hcGifFrameAction);
        this.zDY = (Spinner) findViewById(R.id.ccx);
        this.zDY.setSelection(WXHardCoderJNI.hcGifFrameCPU);
        this.zDZ = (Spinner) findViewById(R.id.ccy);
        this.zDZ.setSelection(WXHardCoderJNI.hcGifFrameIO);
        this.zEa = (CheckBox) findViewById(R.id.ccz);
        this.zEa.setChecked(WXHardCoderJNI.hcGifFrameThr);
        this.zEb = (CheckBox) findViewById(R.id.cd0);
        this.zEb.setChecked(WXHardCoderJNI.hcSNSScrollEnable);
        this.zEc = (EditText) findViewById(R.id.cd2);
        this.zEc.setText(WXHardCoderJNI.hcSNSScrollDelay);
        this.zEd = (EditText) findViewById(R.id.cd1);
        this.zEd.setText(WXHardCoderJNI.hcSNSScrollTimeout);
        this.zEe = (EditText) findViewById(R.id.cd3);
        this.zEe.setText(WXHardCoderJNI.hcSNSScrollAction);
        this.zEf = (Spinner) findViewById(R.id.cd4);
        this.zEf.setSelection(WXHardCoderJNI.hcSNSScrollCPU);
        this.zEg = (Spinner) findViewById(R.id.cd5);
        this.zEg.setSelection(WXHardCoderJNI.hcSNSScrollIO);
        this.zEh = (CheckBox) findViewById(R.id.cd6);
        this.zEh.setChecked(WXHardCoderJNI.hcSNSScrollThr);
        this.zEi = (CheckBox) findViewById(R.id.cd7);
        this.zEi.setChecked(WXHardCoderJNI.hcSNSUserScrollEnable);
        this.zEj = (EditText) findViewById(R.id.cd9);
        this.zEj.setText(WXHardCoderJNI.hcSNSUserScrollDelay);
        this.zEk = (EditText) findViewById(R.id.cd8);
        this.zEk.setText(WXHardCoderJNI.hcSNSUserScrollTimeout);
        this.zEl = (EditText) findViewById(R.id.cd_);
        this.zEl.setText(WXHardCoderJNI.hcSNSUserScrollAction);
        this.zEm = (Spinner) findViewById(R.id.cda);
        this.zEm.setSelection(WXHardCoderJNI.hcSNSUserScrollCPU);
        this.zEn = (Spinner) findViewById(R.id.cdb);
        this.zEn.setSelection(WXHardCoderJNI.hcSNSUserScrollIO);
        this.zEo = (CheckBox) findViewById(R.id.cdc);
        this.zEo.setChecked(WXHardCoderJNI.hcSNSUserScrollThr);
        this.zEp = (CheckBox) findViewById(R.id.cdd);
        this.zEp.setChecked(WXHardCoderJNI.hcSNSMsgScrollEnable);
        this.zEq = (EditText) findViewById(R.id.cdf);
        this.zEq.setText(WXHardCoderJNI.hcSNSMsgScrollDelay);
        this.zEr = (EditText) findViewById(R.id.cde);
        this.zEr.setText(WXHardCoderJNI.hcSNSMsgScrollTimeout);
        this.zEs = (EditText) findViewById(R.id.cdg);
        this.zEs.setText(WXHardCoderJNI.hcSNSMsgScrollAction);
        this.zEt = (Spinner) findViewById(R.id.cdh);
        this.zEt.setSelection(WXHardCoderJNI.hcSNSMsgScrollCPU);
        this.zEu = (Spinner) findViewById(R.id.cdi);
        this.zEu.setSelection(WXHardCoderJNI.hcSNSMsgScrollIO);
        this.zEv = (CheckBox) findViewById(R.id.cdj);
        this.zEv.setChecked(WXHardCoderJNI.hcSNSMsgScrollThr);
        this.zEw = (CheckBox) findViewById(R.id.cdk);
        this.zEw.setChecked(WXHardCoderJNI.hcMediaGalleryScrollEnable);
        this.zEx = (EditText) findViewById(R.id.cdm);
        this.zEx.setText(WXHardCoderJNI.hcMediaGalleryScrollDelay);
        this.zEy = (EditText) findViewById(R.id.cdl);
        this.zEy.setText(WXHardCoderJNI.hcMediaGalleryScrollTimeout);
        this.zEz = (EditText) findViewById(R.id.cdn);
        this.zEz.setText(WXHardCoderJNI.hcMediaGalleryScrollAction);
        this.zEA = (Spinner) findViewById(R.id.cdo);
        this.zEA.setSelection(WXHardCoderJNI.hcMediaGalleryScrollCPU);
        this.zEB = (Spinner) findViewById(R.id.cdp);
        this.zEB.setSelection(WXHardCoderJNI.hcMediaGalleryScrollIO);
        this.zEC = (CheckBox) findViewById(R.id.cdq);
        this.zEC.setChecked(WXHardCoderJNI.hcMediaGalleryScrollThr);
        this.zED = (CheckBox) findViewById(R.id.cdr);
        this.zED.setChecked(WXHardCoderJNI.hcAlbumScrollEnable);
        this.zEE = (EditText) findViewById(R.id.cdt);
        this.zEE.setText(WXHardCoderJNI.hcAlbumScrollDelay);
        this.zEF = (EditText) findViewById(R.id.cds);
        this.zEF.setText(WXHardCoderJNI.hcAlbumScrollTimeout);
        this.zEG = (EditText) findViewById(R.id.cdu);
        this.zEG.setText(WXHardCoderJNI.hcAlbumScrollAction);
        this.zEH = (Spinner) findViewById(R.id.cdv);
        this.zEH.setSelection(WXHardCoderJNI.hcAlbumScrollCPU);
        this.zEI = (Spinner) findViewById(R.id.cdw);
        this.zEI.setSelection(WXHardCoderJNI.hcAlbumScrollIO);
        this.zEJ = (CheckBox) findViewById(R.id.cdx);
        this.zEJ.setChecked(WXHardCoderJNI.hcAlbumScrollThr);
        this.zEK = (CheckBox) findViewById(R.id.cdy);
        this.zEK.setChecked(WXHardCoderJNI.hcBizEnable);
        this.zEL = (EditText) findViewById(R.id.ce0);
        this.zEL.setText(WXHardCoderJNI.hcBizDelay);
        this.zEM = (EditText) findViewById(R.id.cdz);
        this.zEM.setText(WXHardCoderJNI.hcBizTimeout);
        this.zEN = (EditText) findViewById(R.id.ce1);
        this.zEN.setText(WXHardCoderJNI.hcBizAction);
        this.zEO = (Spinner) findViewById(R.id.ce2);
        this.zEO.setSelection(WXHardCoderJNI.hcBizCPU);
        this.zEP = (Spinner) findViewById(R.id.ce3);
        this.zEP.setSelection(WXHardCoderJNI.hcBizIO);
        this.zEQ = (CheckBox) findViewById(R.id.ce4);
        this.zEQ.setChecked(WXHardCoderJNI.hcBizThr);
        this.zCk.setOnClickListener(new OnClickListener() {
            public final void onClick(View view) {
                AppMethodBeat.i(34873);
                boolean isChecked = HardCoderSettingUI.this.zCk.isChecked();
                HardCoderSettingUI.this.zCr.setChecked(isChecked);
                HardCoderSettingUI.this.zDz.setChecked(isChecked);
                HardCoderSettingUI.this.zCy.setChecked(isChecked);
                HardCoderSettingUI.this.zCF.setChecked(isChecked);
                HardCoderSettingUI.this.zCM.setChecked(isChecked);
                HardCoderSettingUI.this.zCT.setChecked(isChecked);
                HardCoderSettingUI.this.zDa.setChecked(isChecked);
                HardCoderSettingUI.this.zDh.setChecked(isChecked);
                HardCoderSettingUI.this.zDp.setChecked(isChecked);
                HardCoderSettingUI.this.zDG.setChecked(isChecked);
                HardCoderSettingUI.this.zDN.setChecked(isChecked);
                HardCoderSettingUI.this.zDU.setChecked(isChecked);
                HardCoderSettingUI.this.zEb.setChecked(isChecked);
                HardCoderSettingUI.this.zEi.setChecked(isChecked);
                HardCoderSettingUI.this.zEp.setChecked(isChecked);
                HardCoderSettingUI.this.zEw.setChecked(isChecked);
                HardCoderSettingUI.this.zED.setChecked(isChecked);
                AppMethodBeat.o(34873);
            }
        });
        AppMethodBeat.o(34876);
    }

    /* Access modifiers changed, original: protected */
    public Dialog onCreateDialog(int i) {
        AppMethodBeat.i(34877);
        switch (i) {
            case 1:
                Dialog timePickerDialog;
                if (this.qmI) {
                    timePickerDialog = new TimePickerDialog(this.mController.ylL, this.qmJ, WXHardCoderJNI.hcBeginTimeHour, WXHardCoderJNI.hcBeginTimeMin, false);
                    AppMethodBeat.o(34877);
                    return timePickerDialog;
                }
                timePickerDialog = new TimePickerDialog(this.mController.ylL, this.qmJ, WXHardCoderJNI.hcEndTimeHour, WXHardCoderJNI.hcBeginTimeMin, false);
                AppMethodBeat.o(34877);
                return timePickerDialog;
            default:
                AppMethodBeat.o(34877);
                return null;
        }
    }

    private static void a(Editor editor) {
        AppMethodBeat.i(34879);
        editor.putBoolean(WXHardCoderJNI.KEY_HC_ENABLE, WXHardCoderJNI.getEnable());
        editor.putBoolean(WXHardCoderJNI.KEY_HC_DEBUG, WXHardCoderJNI.getDebug());
        editor.putInt(WXHardCoderJNI.KEY_HC_RETRY_INTERVAL, WXHardCoderJNI.hcRetryInterval);
        editor.putBoolean(WXHardCoderJNI.KEY_HC_TIME_LIMIT, WXHardCoderJNI.hcTimeLimit);
        editor.putInt(WXHardCoderJNI.KEY_HC_BEGIN_TIME_HOUR, WXHardCoderJNI.hcBeginTimeHour);
        editor.putInt(WXHardCoderJNI.KEY_HC_BEGIN_TIME_MIN, WXHardCoderJNI.hcBeginTimeMin);
        editor.putInt(WXHardCoderJNI.KEY_HC_END_TIME_HOUR, WXHardCoderJNI.hcEndTimeHour);
        editor.putInt(WXHardCoderJNI.KEY_HC_END_TIME_MIN, WXHardCoderJNI.hcEndTimeMin);
        editor.putBoolean(i.KEY_HC_BOOT_ENABLE, WXHardCoderJNI.hcBootEnable);
        editor.putInt(i.KEY_HC_BOOT_DELEY, WXHardCoderJNI.hcBootDelay);
        editor.putInt(i.KEY_HC_BOOT_CPU, WXHardCoderJNI.hcBootCPU);
        editor.putInt(i.KEY_HC_BOOT_IO, WXHardCoderJNI.hcBootIO);
        editor.putBoolean(i.KEY_HC_BOOT_THR, WXHardCoderJNI.hcBootThr);
        editor.putInt(i.KEY_HC_BOOT_TIMEOUT, WXHardCoderJNI.hcBootTimeout);
        editor.putLong(i.KEY_HC_BOOT_ACTION, WXHardCoderJNI.hcBootAction);
        editor.putBoolean(i.KEY_HC_ENTER_CHATTING_ENABLE, WXHardCoderJNI.hcEnterChattingEnable);
        editor.putInt(i.KEY_HC_ENTER_CHATTING_DELEY, WXHardCoderJNI.hcEnterChattingDelay);
        editor.putInt(i.KEY_HC_ENTER_CHATTING_CPU, WXHardCoderJNI.hcEnterChattingCPU);
        editor.putInt(i.KEY_HC_ENTER_CHATTING_IO, WXHardCoderJNI.hcEnterChattingIO);
        editor.putBoolean(i.KEY_HC_ENTER_CHATTING_THR, WXHardCoderJNI.hcEnterChattingThr);
        editor.putInt(i.KEY_HC_ENTER_CHATTING_TIMEOUT, WXHardCoderJNI.hcEnterChattingTimeout);
        editor.putLong(i.KEY_HC_ENTER_CHATTING_ACTION, WXHardCoderJNI.hcEnterChattingAction);
        editor.putBoolean(i.KEY_HC_QUIT_CHATTING_ENABLE, WXHardCoderJNI.hcQuitChattingEnable);
        editor.putInt(i.KEY_HC_QUIT_CHATTING_DELEY, WXHardCoderJNI.hcQuitChattingDelay);
        editor.putInt(i.KEY_HC_QUIT_CHATTING_CPU, WXHardCoderJNI.hcQuitChattingCPU);
        editor.putInt(i.KEY_HC_QUIT_CHATTING_IO, WXHardCoderJNI.hcQuitChattingIO);
        editor.putBoolean(i.KEY_HC_QUIT_CHATTING_THR, WXHardCoderJNI.hcQuitChattingThr);
        editor.putInt(i.KEY_HC_QUIT_CHATTING_TIMEOUT, WXHardCoderJNI.hcQuitChattingTimeout);
        editor.putLong(i.KEY_HC_QUIT_CHATTING_ACTION, WXHardCoderJNI.hcQuitChattingAction);
        editor.putBoolean(i.KEY_HC_SEND_MSG_ENABLE, WXHardCoderJNI.hcSendMsgEnable);
        editor.putInt(i.KEY_HC_SEND_MSG_DELEY, WXHardCoderJNI.hcSendMsgDelay);
        editor.putInt(i.KEY_HC_SEND_MSG_CPU, WXHardCoderJNI.hcSendMsgCPU);
        editor.putInt(i.KEY_HC_SEND_MSG_IO, WXHardCoderJNI.hcSendMsgIO);
        editor.putBoolean(i.KEY_HC_SEND_MSG_THR, WXHardCoderJNI.hcSendMsgThr);
        editor.putInt(i.KEY_HC_SEND_MSG_TIMEOUT, WXHardCoderJNI.hcSendMsgTimeout);
        editor.putLong(i.KEY_HC_SEND_MSG_ACTION, WXHardCoderJNI.hcSendMsgAction);
        editor.putBoolean(i.KEY_HC_SEND_PIC_MSG_ENABLE, WXHardCoderJNI.hcSendPicMsgEnable);
        editor.putInt(i.KEY_HC_SEND_PIC_MSG_DELEY, WXHardCoderJNI.hcSendPicMsgDelay);
        editor.putInt(i.KEY_HC_SEND_PIC_MSG_CPU, WXHardCoderJNI.hcSendPicMsgCPU);
        editor.putInt(i.KEY_HC_SEND_PIC_MSG_IO, WXHardCoderJNI.hcSendPicMsgIO);
        editor.putBoolean(i.KEY_HC_SEND_PIC_MSG_THR, WXHardCoderJNI.hcSendPicMsgThr);
        editor.putInt(i.KEY_HC_SEND_PIC_MSG_TIMEOUT, WXHardCoderJNI.hcSendPicMsgTimeout);
        editor.putLong(i.KEY_HC_SEND_PIC_MSG_ACTION, WXHardCoderJNI.hcSendPicMsgAction);
        editor.putBoolean(i.KEY_HC_RECEIVE_MSG_ENABLE, WXHardCoderJNI.hcReceiveMsgEnable);
        editor.putInt(i.KEY_HC_RECEIVE_MSG_DELEY, WXHardCoderJNI.hcReceiveMsgDelay);
        editor.putInt(i.KEY_HC_RECEIVE_MSG_CPU, WXHardCoderJNI.hcReceiveMsgCPU);
        editor.putInt(i.KEY_HC_RECEIVE_MSG_IO, WXHardCoderJNI.hcReceiveMsgIO);
        editor.putBoolean(i.KEY_HC_RECEIVE_MSG_THR, WXHardCoderJNI.hcReceiveMsgThr);
        editor.putInt(i.KEY_HC_RECEIVE_MSG_TIMEOUT, WXHardCoderJNI.hcReceiveMsgTimeout);
        editor.putLong(i.KEY_HC_RECEIVE_MSG_ACTION, WXHardCoderJNI.hcReceiveMsgAction);
        editor.putBoolean(i.KEY_HC_UPDATE_CHATROOM_ENABLE, WXHardCoderJNI.hcUpdateChatroomEnable);
        editor.putInt(i.KEY_HC_UPDATE_CHATROOM_DELEY, WXHardCoderJNI.hcUpdateChatroomDelay);
        editor.putInt(i.KEY_HC_UPDATE_CHATROOM_CPU, WXHardCoderJNI.hcUpdateChatroomCPU);
        editor.putInt(i.KEY_HC_UPDATE_CHATROOM_IO, WXHardCoderJNI.hcUpdateChatroomIO);
        editor.putBoolean(i.KEY_HC_UPDATE_CHATROOM_THR, WXHardCoderJNI.hcUpdateChatroomThr);
        editor.putInt(i.KEY_HC_UPDATE_CHATROOM_TIMEOUT, WXHardCoderJNI.hcUpdateChatroomTimeout);
        editor.putLong(i.KEY_HC_UPDATE_CHATROOM_ACTION, WXHardCoderJNI.hcUpdateChatroomAction);
        editor.putLong(i.KEY_HC_UPDATE_CHATROOM_MEMBER_COUNT, WXHardCoderJNI.hcUpdateChatroomMemberCount);
        editor.putBoolean(i.KEY_HC_DB_ENABLE, WXHardCoderJNI.hcDBEnable);
        editor.putInt(i.KEY_HC_DB_DELEY_QUERY, WXHardCoderJNI.hcDBDelayQuery);
        editor.putInt(i.KEY_HC_DB_DELEY_WRITE, WXHardCoderJNI.hcDBDelayWrite);
        editor.putInt(i.KEY_HC_DB_CPU, WXHardCoderJNI.hcDBCPU);
        editor.putInt(i.KEY_HC_DB_IO, WXHardCoderJNI.hcDBIO);
        editor.putBoolean(i.KEY_HC_DB_THR, WXHardCoderJNI.hcDBThr);
        editor.putInt(i.KEY_HC_DB_TIMEOUT, WXHardCoderJNI.hcDBTimeout);
        editor.putInt(i.KEY_HC_DB_TIMEOUT, WXHardCoderJNI.hcDBTimeoutBusy);
        editor.putLong(i.KEY_HC_DB_ACTION_QUERY, WXHardCoderJNI.hcDBActionQuery);
        editor.putLong(i.KEY_HC_DB_ACTION_WRITE, WXHardCoderJNI.hcDBActionWrite);
        editor.putBoolean(i.KEY_HC_ENCODE_VIDEO_ENABLE, WXHardCoderJNI.hcEncodeVideoEnable);
        editor.putInt(i.KEY_HC_ENCODE_VIDEO_DELEY, WXHardCoderJNI.hcEncodeVideoDelay);
        editor.putInt(i.KEY_HC_ENCODE_VIDEO_CPU, WXHardCoderJNI.hcEncodeVideoCPU);
        editor.putInt(i.KEY_HC_ENCODE_VIDEO_IO, WXHardCoderJNI.hcEncodeVideoIO);
        editor.putBoolean(i.KEY_HC_ENCODE_VIDEO_THR, WXHardCoderJNI.hcEncodeVideoThr);
        editor.putInt(i.KEY_HC_ENCODE_VIDEO_TIMEOUT, WXHardCoderJNI.hcEncodeVideoTimeout);
        editor.putLong(i.KEY_HC_ENCODE_VIDEO_ACTION, WXHardCoderJNI.hcEncodeVideoAction);
        editor.putBoolean(i.KEY_HC_DECODE_PIC_ENABLE, WXHardCoderJNI.hcDecodePicEnable);
        editor.putInt(i.KEY_HC_DECODE_PIC_DELEY, WXHardCoderJNI.hcDecodePicDelay);
        editor.putInt(i.KEY_HC_DECODE_PIC_CPU, WXHardCoderJNI.hcDecodePicCPU);
        editor.putInt(i.KEY_HC_DECODE_PIC_IO, WXHardCoderJNI.hcDecodePicIO);
        editor.putBoolean(i.KEY_HC_DECODE_PIC_THR, WXHardCoderJNI.hcDecodePicThr);
        editor.putInt(i.KEY_HC_DECODE_PIC_TIMEOUT, WXHardCoderJNI.hcDecodePicTimeout);
        editor.putLong(i.KEY_HC_DECODE_PIC_ACTION, WXHardCoderJNI.hcDecodePicAction);
        editor.putBoolean(i.KEY_HC_GIF_ENABLE, WXHardCoderJNI.hcGifEnable);
        editor.putInt(i.KEY_HC_GIF_DELEY, WXHardCoderJNI.hcGifDelay);
        editor.putInt(i.KEY_HC_GIF_CPU, WXHardCoderJNI.hcGifCPU);
        editor.putInt(i.KEY_HC_GIF_IO, WXHardCoderJNI.hcGifIO);
        editor.putBoolean(i.KEY_HC_GIF_THR, WXHardCoderJNI.hcGifThr);
        editor.putInt(i.KEY_HC_GIF_TIMEOUT, WXHardCoderJNI.hcGifTimeout);
        editor.putLong(i.KEY_HC_GIF_ACTION, WXHardCoderJNI.hcGifAction);
        editor.putBoolean(i.KEY_HC_GIF_FRAME_ENABLE, WXHardCoderJNI.hcGifFrameEnable);
        editor.putInt(i.KEY_HC_GIF_FRAME_DELEY, WXHardCoderJNI.hcGifFrameDelay);
        editor.putInt(i.KEY_HC_GIF_FRAME_CPU, WXHardCoderJNI.hcGifFrameCPU);
        editor.putInt(i.KEY_HC_GIF_FRAME_IO, WXHardCoderJNI.hcGifFrameIO);
        editor.putBoolean(i.KEY_HC_GIF_FRAME_THR, WXHardCoderJNI.hcGifFrameThr);
        editor.putInt(i.KEY_HC_GIF_FRAME_TIMEOUT, WXHardCoderJNI.hcGifFrameTimeout);
        editor.putLong(i.KEY_HC_GIF_FRAME_ACTION, WXHardCoderJNI.hcGifFrameAction);
        editor.putBoolean(i.KEY_HC_SNS_SCROLL_ENABLE, WXHardCoderJNI.hcSNSScrollEnable);
        editor.putInt(i.KEY_HC_SNS_SCROLL_DELEY, WXHardCoderJNI.hcSNSScrollDelay);
        editor.putInt(i.KEY_HC_SNS_SCROLL_CPU, WXHardCoderJNI.hcSNSScrollCPU);
        editor.putInt(i.KEY_HC_SNS_SCROLL_IO, WXHardCoderJNI.hcSNSScrollIO);
        editor.putBoolean(i.KEY_HC_SNS_SCROLL_THR, WXHardCoderJNI.hcSNSScrollThr);
        editor.putInt(i.KEY_HC_SNS_SCROLL_TIMEOUT, WXHardCoderJNI.hcSNSScrollTimeout);
        editor.putLong(i.KEY_HC_SNS_SCROLL_ACTION, WXHardCoderJNI.hcSNSScrollAction);
        editor.putBoolean(i.KEY_HC_SNS_USER_SCROLL_ENABLE, WXHardCoderJNI.hcSNSUserScrollEnable);
        editor.putInt(i.KEY_HC_SNS_USER_SCROLL_DELEY, WXHardCoderJNI.hcSNSUserScrollDelay);
        editor.putInt(i.KEY_HC_SNS_USER_SCROLL_CPU, WXHardCoderJNI.hcSNSUserScrollCPU);
        editor.putInt(i.KEY_HC_SNS_USER_SCROLL_IO, WXHardCoderJNI.hcSNSUserScrollIO);
        editor.putBoolean(i.KEY_HC_SNS_USER_SCROLL_THR, WXHardCoderJNI.hcSNSUserScrollThr);
        editor.putInt(i.KEY_HC_SNS_USER_SCROLL_TIMEOUT, WXHardCoderJNI.hcSNSUserScrollTimeout);
        editor.putLong(i.KEY_HC_SNS_USER_SCROLL_ACTION, WXHardCoderJNI.hcSNSUserScrollAction);
        editor.putBoolean(i.KEY_HC_SNS_MSG_SCROLL_ENABLE, WXHardCoderJNI.hcSNSMsgScrollEnable);
        editor.putInt(i.KEY_HC_SNS_MSG_SCROLL_DELEY, WXHardCoderJNI.hcSNSMsgScrollDelay);
        editor.putInt(i.KEY_HC_SNS_MSG_SCROLL_CPU, WXHardCoderJNI.hcSNSMsgScrollCPU);
        editor.putInt(i.KEY_HC_SNS_MSG_SCROLL_IO, WXHardCoderJNI.hcSNSMsgScrollIO);
        editor.putBoolean(i.KEY_HC_SNS_MSG_SCROLL_THR, WXHardCoderJNI.hcSNSMsgScrollThr);
        editor.putInt(i.KEY_HC_SNS_MSG_SCROLL_TIMEOUT, WXHardCoderJNI.hcSNSMsgScrollTimeout);
        editor.putLong(i.KEY_HC_SNS_MSG_SCROLL_ACTION, WXHardCoderJNI.hcSNSMsgScrollAction);
        editor.putBoolean(i.KEY_HC_MEDIA_GALLERY_SCROLL_ENABLE, WXHardCoderJNI.hcMediaGalleryScrollEnable);
        editor.putInt(i.KEY_HC_MEDIA_GALLERY_SCROLL_DELEY, WXHardCoderJNI.hcMediaGalleryScrollDelay);
        editor.putInt(i.KEY_HC_MEDIA_GALLERY_SCROLL_CPU, WXHardCoderJNI.hcMediaGalleryScrollCPU);
        editor.putInt(i.KEY_HC_MEDIA_GALLERY_SCROLL_IO, WXHardCoderJNI.hcMediaGalleryScrollIO);
        editor.putBoolean(i.KEY_HC_MEDIA_GALLERY_SCROLL_THR, WXHardCoderJNI.hcMediaGalleryScrollThr);
        editor.putInt(i.KEY_HC_MEDIA_GALLERY_SCROLL_TIMEOUT, WXHardCoderJNI.hcMediaGalleryScrollTimeout);
        editor.putLong(i.KEY_HC_MEDIA_GALLERY_SCROLL_ACTION, WXHardCoderJNI.hcMediaGalleryScrollAction);
        editor.putBoolean(i.KEY_HC_ALBUM_SCROLL_ENABLE, WXHardCoderJNI.hcAlbumScrollEnable);
        editor.putInt(i.KEY_HC_ALBUM_SCROLL_DELEY, WXHardCoderJNI.hcAlbumScrollDelay);
        editor.putInt(i.KEY_HC_ALBUM_SCROLL_CPU, WXHardCoderJNI.hcAlbumScrollCPU);
        editor.putInt(i.KEY_HC_ALBUM_SCROLL_IO, WXHardCoderJNI.hcAlbumScrollIO);
        editor.putBoolean(i.KEY_HC_ALBUM_SCROLL_THR, WXHardCoderJNI.hcAlbumScrollThr);
        editor.putInt(i.KEY_HC_ALBUM_SCROLL_TIMEOUT, WXHardCoderJNI.hcAlbumScrollTimeout);
        editor.putLong(i.KEY_HC_ALBUM_SCROLL_ACTION, WXHardCoderJNI.hcAlbumScrollAction);
        editor.apply();
        AppMethodBeat.o(34879);
    }

    public final int getLayoutId() {
        return R.layout.a6m;
    }

    private static String c(Context context, int i, int i2) {
        AppMethodBeat.i(34880);
        String h = aa.h(context.getSharedPreferences(ah.doA(), 0));
        String dor = aa.dor();
        if (h.equalsIgnoreCase("zh_CN") || (h.equalsIgnoreCase("language_default") && "zh_CN".equalsIgnoreCase(dor))) {
            int i3;
            if (i > 12) {
                i3 = i - 12;
            } else {
                i3 = i;
            }
            h = h.r(context, (((long) i) * 3600000) + (((long) i2) * 60000)) + String.format("%02d:%02d", new Object[]{Integer.valueOf(i3), Integer.valueOf(i2)});
            AppMethodBeat.o(34880);
            return h;
        }
        h = DateFormat.getTimeInstance(3, aa.amw(h)).format(new Time(i, i2, 0));
        AppMethodBeat.o(34880);
        return h;
    }

    public void onDestroy() {
        AppMethodBeat.i(34878);
        ab.i("HardCoderSettingUI", "save");
        if (this.zCk.isChecked() && !WXHardCoderJNI.getEnable()) {
            WXHardCoderJNI.setHcEnable(this.zCk.isChecked());
            WXHardCoderJNI.initHardCoder(a.bFR(), a.bFR());
        }
        WXHardCoderJNI.setDebug(this.zCm.isChecked());
        WXHardCoderJNI.setHcEnable(this.zCk.isChecked());
        WXHardCoderJNI.hcRetryInterval = bo.getInt(this.zCl.getText().toString(), WXHardCoderJNI.hcRetryInterval);
        if (WXHardCoderJNI.isCheckEnv()) {
            WXHardCoderJNI.setDebug(WXHardCoderJNI.getDebug());
            WXHardCoderJNI.setHcEnable(WXHardCoderJNI.getEnable());
            WXHardCoderJNI.setRetryConnectInterval(WXHardCoderJNI.hcRetryInterval);
        }
        WXHardCoderJNI.hcTimeLimit = this.zCo.isChecked();
        WXHardCoderJNI.hcBootEnable = this.zCr.isChecked();
        WXHardCoderJNI.hcBootDelay = bo.getInt(this.zCs.getText().toString(), WXHardCoderJNI.hcBootDelay);
        WXHardCoderJNI.hcBootCPU = this.zCv.getSelectedItemPosition();
        WXHardCoderJNI.hcBootIO = this.zCw.getSelectedItemPosition();
        WXHardCoderJNI.hcBootThr = this.zCx.isChecked();
        WXHardCoderJNI.hcBootTimeout = bo.getInt(this.zCt.getText().toString(), WXHardCoderJNI.hcBootTimeout);
        WXHardCoderJNI.hcBootAction = bo.getLong(this.zCu.getText().toString(), WXHardCoderJNI.hcBootAction);
        WXHardCoderJNI.hcEnterChattingEnable = this.zCy.isChecked();
        WXHardCoderJNI.hcEnterChattingDelay = bo.getInt(this.zCz.getText().toString(), WXHardCoderJNI.hcEnterChattingDelay);
        WXHardCoderJNI.hcEnterChattingCPU = this.zCC.getSelectedItemPosition();
        WXHardCoderJNI.hcEnterChattingIO = this.zCD.getSelectedItemPosition();
        WXHardCoderJNI.hcEnterChattingThr = this.zCE.isChecked();
        WXHardCoderJNI.hcEnterChattingTimeout = bo.getInt(this.zCA.getText().toString(), WXHardCoderJNI.hcEnterChattingTimeout);
        WXHardCoderJNI.hcEnterChattingAction = bo.getLong(this.zCB.getText().toString(), WXHardCoderJNI.hcEnterChattingAction);
        WXHardCoderJNI.hcQuitChattingEnable = this.zCF.isChecked();
        WXHardCoderJNI.hcQuitChattingDelay = bo.getInt(this.zCG.getText().toString(), WXHardCoderJNI.hcQuitChattingDelay);
        WXHardCoderJNI.hcQuitChattingCPU = this.zCJ.getSelectedItemPosition();
        WXHardCoderJNI.hcQuitChattingIO = this.zCK.getSelectedItemPosition();
        WXHardCoderJNI.hcQuitChattingThr = this.zCL.isChecked();
        WXHardCoderJNI.hcQuitChattingTimeout = bo.getInt(this.zCH.getText().toString(), WXHardCoderJNI.hcQuitChattingTimeout);
        WXHardCoderJNI.hcQuitChattingAction = bo.getLong(this.zCI.getText().toString(), WXHardCoderJNI.hcQuitChattingAction);
        WXHardCoderJNI.hcSendMsgEnable = this.zCM.isChecked();
        WXHardCoderJNI.hcSendMsgDelay = bo.getInt(this.zCN.getText().toString(), WXHardCoderJNI.hcSendMsgDelay);
        WXHardCoderJNI.hcSendMsgCPU = this.zCQ.getSelectedItemPosition();
        WXHardCoderJNI.hcSendMsgIO = this.zCR.getSelectedItemPosition();
        WXHardCoderJNI.hcSendMsgThr = this.zCS.isChecked();
        WXHardCoderJNI.hcSendMsgTimeout = bo.getInt(this.zCO.getText().toString(), WXHardCoderJNI.hcSendMsgTimeout);
        WXHardCoderJNI.hcSendMsgAction = bo.getLong(this.zCP.getText().toString(), WXHardCoderJNI.hcSendMsgAction);
        WXHardCoderJNI.hcSendPicMsgEnable = this.zCT.isChecked();
        WXHardCoderJNI.hcSendPicMsgDelay = bo.getInt(this.zCU.getText().toString(), WXHardCoderJNI.hcSendPicMsgDelay);
        WXHardCoderJNI.hcSendPicMsgCPU = this.zCX.getSelectedItemPosition();
        WXHardCoderJNI.hcSendPicMsgIO = this.zCY.getSelectedItemPosition();
        WXHardCoderJNI.hcSendPicMsgThr = this.zCZ.isChecked();
        WXHardCoderJNI.hcSendPicMsgTimeout = bo.getInt(this.zCV.getText().toString(), WXHardCoderJNI.hcSendPicMsgTimeout);
        WXHardCoderJNI.hcSendPicMsgAction = bo.getLong(this.zCW.getText().toString(), WXHardCoderJNI.hcSendPicMsgAction);
        WXHardCoderJNI.hcReceiveMsgEnable = this.zDa.isChecked();
        WXHardCoderJNI.hcReceiveMsgDelay = bo.getInt(this.zDb.getText().toString(), WXHardCoderJNI.hcReceiveMsgDelay);
        WXHardCoderJNI.hcReceiveMsgCPU = this.zDe.getSelectedItemPosition();
        WXHardCoderJNI.hcReceiveMsgIO = this.zDf.getSelectedItemPosition();
        WXHardCoderJNI.hcReceiveMsgThr = this.zDg.isChecked();
        WXHardCoderJNI.hcReceiveMsgTimeout = bo.getInt(this.zDc.getText().toString(), WXHardCoderJNI.hcReceiveMsgTimeout);
        WXHardCoderJNI.hcReceiveMsgAction = bo.getLong(this.zDd.getText().toString(), WXHardCoderJNI.hcReceiveMsgAction);
        WXHardCoderJNI.hcUpdateChatroomEnable = this.zDh.isChecked();
        WXHardCoderJNI.hcUpdateChatroomDelay = bo.getInt(this.zDi.getText().toString(), WXHardCoderJNI.hcUpdateChatroomDelay);
        WXHardCoderJNI.hcUpdateChatroomCPU = this.zDl.getSelectedItemPosition();
        WXHardCoderJNI.hcUpdateChatroomIO = this.zDm.getSelectedItemPosition();
        WXHardCoderJNI.hcUpdateChatroomThr = this.zDn.isChecked();
        WXHardCoderJNI.hcUpdateChatroomTimeout = bo.getInt(this.zDj.getText().toString(), WXHardCoderJNI.hcUpdateChatroomTimeout);
        WXHardCoderJNI.hcUpdateChatroomAction = bo.getLong(this.zDk.getText().toString(), WXHardCoderJNI.hcUpdateChatroomAction);
        WXHardCoderJNI.hcUpdateChatroomMemberCount = bo.getLong(this.zDo.getText().toString(), WXHardCoderJNI.hcUpdateChatroomMemberCount);
        WXHardCoderJNI.hcDBEnable = this.zDp.isChecked();
        WXHardCoderJNI.hcDBDelayQuery = bo.getInt(this.zDq.getText().toString(), WXHardCoderJNI.hcDBDelayQuery);
        WXHardCoderJNI.hcDBDelayWrite = bo.getInt(this.zDr.getText().toString(), WXHardCoderJNI.hcDBDelayWrite);
        WXHardCoderJNI.hcDBCPU = this.zCv.getSelectedItemPosition();
        WXHardCoderJNI.hcDBIO = this.zCw.getSelectedItemPosition();
        WXHardCoderJNI.hcDBThr = this.zCx.isChecked();
        WXHardCoderJNI.hcDBTimeout = bo.getInt(this.zDs.getText().toString(), WXHardCoderJNI.hcDBTimeout);
        WXHardCoderJNI.hcDBTimeoutBusy = bo.getInt(this.zDt.getText().toString(), WXHardCoderJNI.hcDBTimeoutBusy);
        WXHardCoderJNI.hcDBActionQuery = bo.getLong(this.zDu.getText().toString(), WXHardCoderJNI.hcDBActionQuery);
        WXHardCoderJNI.hcDBActionWrite = bo.getLong(this.zDv.getText().toString(), WXHardCoderJNI.hcDBActionWrite);
        WXHardCoderJNI.hcEncodeVideoEnable = this.zDz.isChecked();
        WXHardCoderJNI.hcEncodeVideoDelay = bo.getInt(this.zDA.getText().toString(), WXHardCoderJNI.hcEncodeVideoDelay);
        WXHardCoderJNI.hcEncodeVideoCPU = this.zDD.getSelectedItemPosition();
        WXHardCoderJNI.hcEncodeVideoIO = this.zDE.getSelectedItemPosition();
        WXHardCoderJNI.hcEncodeVideoThr = this.zDF.isChecked();
        WXHardCoderJNI.hcEncodeVideoTimeout = bo.getInt(this.zDB.getText().toString(), WXHardCoderJNI.hcEncodeVideoTimeout);
        WXHardCoderJNI.hcEncodeVideoAction = bo.getLong(this.zDC.getText().toString(), WXHardCoderJNI.hcEncodeVideoAction);
        WXHardCoderJNI.hcDecodePicEnable = this.zDG.isChecked();
        WXHardCoderJNI.hcDecodePicDelay = bo.getInt(this.zDH.getText().toString(), WXHardCoderJNI.hcDecodePicDelay);
        WXHardCoderJNI.hcDecodePicCPU = this.zDK.getSelectedItemPosition();
        WXHardCoderJNI.hcDecodePicIO = this.zDL.getSelectedItemPosition();
        WXHardCoderJNI.hcDecodePicThr = this.zDM.isChecked();
        WXHardCoderJNI.hcDecodePicTimeout = bo.getInt(this.zDI.getText().toString(), WXHardCoderJNI.hcDecodePicTimeout);
        WXHardCoderJNI.hcDecodePicAction = bo.getLong(this.zDJ.getText().toString(), WXHardCoderJNI.hcDecodePicAction);
        WXHardCoderJNI.hcGifEnable = this.zDN.isChecked();
        WXHardCoderJNI.hcGifDelay = bo.getInt(this.zDO.getText().toString(), WXHardCoderJNI.hcGifDelay);
        WXHardCoderJNI.hcGifCPU = this.zDR.getSelectedItemPosition();
        WXHardCoderJNI.hcGifIO = this.zDS.getSelectedItemPosition();
        WXHardCoderJNI.hcGifThr = this.zDT.isChecked();
        WXHardCoderJNI.hcGifTimeout = bo.getInt(this.zDP.getText().toString(), WXHardCoderJNI.hcGifTimeout);
        WXHardCoderJNI.hcGifAction = bo.getLong(this.zDQ.getText().toString(), WXHardCoderJNI.hcGifAction);
        WXHardCoderJNI.hcGifFrameEnable = this.zDU.isChecked();
        WXHardCoderJNI.hcGifFrameDelay = bo.getInt(this.zDV.getText().toString(), WXHardCoderJNI.hcGifFrameDelay);
        WXHardCoderJNI.hcGifFrameCPU = this.zDY.getSelectedItemPosition();
        WXHardCoderJNI.hcGifFrameIO = this.zDZ.getSelectedItemPosition();
        WXHardCoderJNI.hcGifFrameThr = this.zEa.isChecked();
        WXHardCoderJNI.hcGifFrameTimeout = bo.getInt(this.zDW.getText().toString(), WXHardCoderJNI.hcGifFrameTimeout);
        WXHardCoderJNI.hcGifFrameAction = bo.getLong(this.zDX.getText().toString(), WXHardCoderJNI.hcGifFrameAction);
        WXHardCoderJNI.hcSNSScrollEnable = this.zEb.isChecked();
        WXHardCoderJNI.hcSNSScrollDelay = bo.getInt(this.zEc.getText().toString(), WXHardCoderJNI.hcSNSScrollDelay);
        WXHardCoderJNI.hcSNSScrollCPU = this.zEf.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSScrollIO = this.zEg.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSScrollThr = this.zEh.isChecked();
        WXHardCoderJNI.hcSNSScrollTimeout = bo.getInt(this.zEd.getText().toString(), WXHardCoderJNI.hcSNSScrollTimeout);
        WXHardCoderJNI.hcSNSScrollAction = bo.getLong(this.zEe.getText().toString(), WXHardCoderJNI.hcSNSScrollAction);
        WXHardCoderJNI.hcSNSUserScrollEnable = this.zEi.isChecked();
        WXHardCoderJNI.hcSNSUserScrollDelay = bo.getInt(this.zEj.getText().toString(), WXHardCoderJNI.hcSNSUserScrollDelay);
        WXHardCoderJNI.hcSNSUserScrollCPU = this.zEm.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSUserScrollIO = this.zEn.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSUserScrollThr = this.zEo.isChecked();
        WXHardCoderJNI.hcSNSUserScrollTimeout = bo.getInt(this.zEk.getText().toString(), WXHardCoderJNI.hcSNSUserScrollTimeout);
        WXHardCoderJNI.hcSNSUserScrollAction = bo.getLong(this.zEl.getText().toString(), WXHardCoderJNI.hcSNSUserScrollAction);
        WXHardCoderJNI.hcSNSMsgScrollEnable = this.zEp.isChecked();
        WXHardCoderJNI.hcSNSMsgScrollDelay = bo.getInt(this.zEq.getText().toString(), WXHardCoderJNI.hcSNSMsgScrollDelay);
        WXHardCoderJNI.hcSNSMsgScrollCPU = this.zEt.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSMsgScrollIO = this.zEu.getSelectedItemPosition();
        WXHardCoderJNI.hcSNSMsgScrollThr = this.zEv.isChecked();
        WXHardCoderJNI.hcSNSMsgScrollTimeout = bo.getInt(this.zEr.getText().toString(), WXHardCoderJNI.hcSNSMsgScrollTimeout);
        WXHardCoderJNI.hcSNSMsgScrollAction = bo.getLong(this.zEs.getText().toString(), WXHardCoderJNI.hcSNSMsgScrollAction);
        WXHardCoderJNI.hcMediaGalleryScrollEnable = this.zEw.isChecked();
        WXHardCoderJNI.hcMediaGalleryScrollDelay = bo.getInt(this.zEx.getText().toString(), WXHardCoderJNI.hcMediaGalleryScrollDelay);
        WXHardCoderJNI.hcMediaGalleryScrollCPU = this.zEA.getSelectedItemPosition();
        WXHardCoderJNI.hcMediaGalleryScrollIO = this.zEB.getSelectedItemPosition();
        WXHardCoderJNI.hcMediaGalleryScrollThr = this.zEC.isChecked();
        WXHardCoderJNI.hcMediaGalleryScrollTimeout = bo.getInt(this.zEy.getText().toString(), WXHardCoderJNI.hcMediaGalleryScrollTimeout);
        WXHardCoderJNI.hcMediaGalleryScrollAction = bo.getLong(this.zEz.getText().toString(), WXHardCoderJNI.hcMediaGalleryScrollAction);
        WXHardCoderJNI.hcAlbumScrollEnable = this.zED.isChecked();
        WXHardCoderJNI.hcAlbumScrollDelay = bo.getInt(this.zEE.getText().toString(), WXHardCoderJNI.hcAlbumScrollDelay);
        WXHardCoderJNI.hcAlbumScrollCPU = this.zEH.getSelectedItemPosition();
        WXHardCoderJNI.hcAlbumScrollIO = this.zEI.getSelectedItemPosition();
        WXHardCoderJNI.hcAlbumScrollThr = this.zEJ.isChecked();
        WXHardCoderJNI.hcAlbumScrollTimeout = bo.getInt(this.zEF.getText().toString(), WXHardCoderJNI.hcAlbumScrollTimeout);
        WXHardCoderJNI.hcAlbumScrollAction = bo.getLong(this.zEG.getText().toString(), WXHardCoderJNI.hcAlbumScrollAction);
        WXHardCoderJNI.hcBizEnable = this.zEK.isChecked();
        WXHardCoderJNI.hcBizDelay = bo.getInt(this.zEL.getText().toString(), WXHardCoderJNI.hcBizDelay);
        WXHardCoderJNI.hcBizCPU = this.zEO.getSelectedItemPosition();
        WXHardCoderJNI.hcBizIO = this.zEP.getSelectedItemPosition();
        WXHardCoderJNI.hcBizThr = this.zEQ.isChecked();
        WXHardCoderJNI.hcBizTimeout = bo.getInt(this.zEM.getText().toString(), WXHardCoderJNI.hcBizTimeout);
        WXHardCoderJNI.hcBizAction = bo.getLong(this.zEN.getText().toString(), WXHardCoderJNI.hcBizAction);
        a(this.mController.ylL.getSharedPreferences(WXHardCoderJNI.SETTING_SP_FILE, 0).edit());
        WXHardCoderJNI.reloadSPConfig(WXHardCoderJNI.RELOAD_SCENE_SETTING);
        super.onDestroy();
        AppMethodBeat.o(34878);
    }
}
