package com.tencent.p177mm.plugin.sns.p520ui;

import com.tencent.p177mm.p264n.C7486a;
import com.tencent.p177mm.plugin.sns.data.C43538d;
import com.tencent.p177mm.plugin.sns.storage.C21980a;
import com.tencent.p177mm.plugin.sns.storage.C21984b;
import com.tencent.p177mm.plugin.sns.storage.C46236n;
import com.tencent.p177mm.protocal.protobuf.TimeLineObject;
import com.tencent.p177mm.protocal.protobuf.bav;
import com.tencent.p177mm.protocal.protobuf.cbf;
import com.tencent.p177mm.vending.p638d.C5683b;
import com.tencent.p177mm.vending.p644j.C5710a;

/* renamed from: com.tencent.mm.plugin.sns.ui.av */
public final class C13633av {
    public int auo;
    public String igi;
    public String mAppName;
    public cbf qBX;
    public C46236n qBY;
    public TimeLineObject qCc;
    public String rAA;
    public C21980a rAB;
    public C21984b rAC;
    public String rAD;
    public String rAE;
    public String rAF;
    public String rAG;
    public String rAH;
    public boolean rAI;
    public boolean rAJ;
    public boolean rAK;
    public int rAL;
    public boolean rAM;
    public String rAN;
    public boolean rAO;
    public boolean rAP;
    public boolean rAQ;
    public boolean rAR;
    public String rAS;
    public String rAT;
    public boolean rAU;
    public boolean rAV;
    public int rAW;
    public boolean rAX;
    public boolean rAY;
    public String rAZ;
    public C43538d rAp;
    public CharSequence rAq = null;
    public C7486a rAr;
    public String rAs;
    public long rAt;
    public String rAu;
    public int rAv;
    public int rAw;
    public int rAx;
    public boolean rAy;
    public String rAz;
    public boolean rBa;
    public boolean rBb;
    public int rBc;
    public double rBd;
    public C5683b<C5710a> rBe;
    public C5683b<C5710a> rBf;
    public C5683b<C5710a> rBg;
    public boolean rBh;
    public String rBi;
    public bav rBj;
    public boolean rgZ;
    public String riA;
}
